/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * +protobuf.options.(gogoproto.goproto_stringer)=false
 *
 * @param group 
 * @param resource 
 * @param version 
 */
@Serializable

data class ApiMachineryGroupVersionResource (

    @SerialName(value = "group")
    val group: kotlin.String? = null,

    @SerialName(value = "resource")
    val resource: kotlin.String? = null,

    @SerialName(value = "version")
    val version: kotlin.String? = null

) {


}

