/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
 *
 * @param key key is the label key that the selector applies to.
 * @param `operator` operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
 * @param propertyValues values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
 */
@Serializable

data class ApiMachineryLabelSelectorRequirement (

    /* key is the label key that the selector applies to. */
    @SerialName(value = "key")
    val key: kotlin.String,

    /* operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist. */
    @SerialName(value = "operator")
    val `operator`: kotlin.String,

    /* values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch. */
    @SerialName(value = "values")
    val propertyValues: kotlin.collections.List<kotlin.String>? = null

) {


}

