/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ApiMachineryLabelSelectorRequirement

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
 *
 * @param matchExpressions matchExpressions is a list of label selector requirements. The requirements are ANDed.
 * @param matchLabels matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \"key\", the operator is \"In\", and the values array contains only \"value\". The requirements are ANDed.
 */
@Serializable

data class ApiMachineryLabelSelector (

    /* matchExpressions is a list of label selector requirements. The requirements are ANDed. */
    @SerialName(value = "matchExpressions")
    val matchExpressions: kotlin.collections.List<ApiMachineryLabelSelectorRequirement>? = null,

    /* matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \"key\", the operator is \"In\", and the values array contains only \"value\". The requirements are ANDed. */
    @SerialName(value = "matchLabels")
    val matchLabels: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

