/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.TarStrategy

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * ArchiveStrategy describes how to archive files/directory when saving artifacts
 *
 * @param none NoneStrategy indicates to skip tar process and upload the files or directory tree as independent files. Note that if the artifact is a directory, the artifact driver must support the ability to save/load the directory appropriately.
 * @param tar 
 * @param zip ZipStrategy will unzip zipped input artifacts
 */
@Serializable

data class ArchiveStrategy (

    /* NoneStrategy indicates to skip tar process and upload the files or directory tree as independent files. Note that if the artifact is a directory, the artifact driver must support the ability to save/load the directory appropriately. */
    @Contextual @SerialName(value = "none")
    val none: kotlin.Any? = null,

    @SerialName(value = "tar")
    val tar: TarStrategy? = null,

    /* ZipStrategy will unzip zipped input artifacts */
    @Contextual @SerialName(value = "zip")
    val zip: kotlin.Any? = null

) {


}

