/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsSlackSender
import io.heapy.argo.client.models.ArgoEventsSlackThread
import io.heapy.argo.client.models.ArgoEventsTriggerParameter
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * SlackTrigger refers to the specification of the slack notification trigger.
 *
 * @param attachments 
 * @param blocks 
 * @param channel 
 * @param message 
 * @param parameters 
 * @param sender 
 * @param slackToken 
 * @param thread 
 */
@Serializable

data class ArgoEventsSlackTrigger (

    @SerialName(value = "attachments")
    val attachments: kotlin.String? = null,

    @SerialName(value = "blocks")
    val blocks: kotlin.String? = null,

    @SerialName(value = "channel")
    val channel: kotlin.String? = null,

    @SerialName(value = "message")
    val message: kotlin.String? = null,

    @SerialName(value = "parameters")
    val parameters: kotlin.collections.List<ArgoEventsTriggerParameter>? = null,

    @SerialName(value = "sender")
    val sender: ArgoEventsSlackSender? = null,

    @SerialName(value = "slackToken")
    val slackToken: KubernetesSecretKeySelector? = null,

    @SerialName(value = "thread")
    val thread: ArgoEventsSlackThread? = null

) {


}

