/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsEventSourceFilter
import io.heapy.argo.client.models.ArgoEventsGithubAppCreds
import io.heapy.argo.client.models.ArgoEventsOwnedRepositories
import io.heapy.argo.client.models.ArgoEventsWebhookContext
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param active 
 * @param apiToken 
 * @param contentType 
 * @param deleteHookOnFinish 
 * @param events 
 * @param filter 
 * @param githubApp 
 * @param githubBaseURL 
 * @param githubUploadURL 
 * @param id 
 * @param insecure 
 * @param metadata 
 * @param organizations Organizations holds the names of organizations (used for organization level webhooks). Not required if Repositories is set.
 * @param owner 
 * @param repositories Repositories holds the information of repositories, which uses repo owner as the key, and list of repo names as the value. Not required if Organizations is set.
 * @param repository 
 * @param webhook 
 * @param webhookSecret 
 */
@Serializable

data class ArgoEventsGithubEventSource (

    @SerialName(value = "active")
    val active: kotlin.Boolean? = null,

    @SerialName(value = "apiToken")
    val apiToken: KubernetesSecretKeySelector? = null,

    @SerialName(value = "contentType")
    val contentType: kotlin.String? = null,

    @SerialName(value = "deleteHookOnFinish")
    val deleteHookOnFinish: kotlin.Boolean? = null,

    @SerialName(value = "events")
    val events: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "filter")
    val filter: ArgoEventsEventSourceFilter? = null,

    @SerialName(value = "githubApp")
    val githubApp: ArgoEventsGithubAppCreds? = null,

    @SerialName(value = "githubBaseURL")
    val githubBaseURL: kotlin.String? = null,

    @SerialName(value = "githubUploadURL")
    val githubUploadURL: kotlin.String? = null,

    @SerialName(value = "id")
    val id: kotlin.String? = null,

    @SerialName(value = "insecure")
    val insecure: kotlin.Boolean? = null,

    @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Organizations holds the names of organizations (used for organization level webhooks). Not required if Repositories is set. */
    @SerialName(value = "organizations")
    val organizations: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "owner")
    val owner: kotlin.String? = null,

    /* Repositories holds the information of repositories, which uses repo owner as the key, and list of repo names as the value. Not required if Organizations is set. */
    @SerialName(value = "repositories")
    val repositories: kotlin.collections.List<ArgoEventsOwnedRepositories>? = null,

    @SerialName(value = "repository")
    val repository: kotlin.String? = null,

    @SerialName(value = "webhook")
    val webhook: ArgoEventsWebhookContext? = null,

    @SerialName(value = "webhookSecret")
    val webhookSecret: KubernetesSecretKeySelector? = null

) {


}

