/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param key 
 * @param name 
 */
@Serializable

data class ArgoEventsS3Bucket (

    @SerialName(value = "key")
    val key: kotlin.String? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null

) {


}

