/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsBackoff
import io.heapy.argo.client.models.ArgoEventsTLSConfig
import io.heapy.argo.client.models.ArgoEventsTriggerParameter
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * PulsarTrigger refers to the specification of the Pulsar trigger.
 *
 * @param authAthenzParams 
 * @param authAthenzSecret 
 * @param authTokenSecret 
 * @param connectionBackoff 
 * @param parameters Parameters is the list of parameters that is applied to resolved Kafka trigger object.
 * @param payload Payload is the list of key-value extracted from an event payload to construct the request payload.
 * @param tls 
 * @param tlsAllowInsecureConnection 
 * @param tlsTrustCertsSecret 
 * @param tlsValidateHostname 
 * @param topic 
 * @param url 
 */
@Serializable

data class ArgoEventsPulsarTrigger (

    @SerialName(value = "authAthenzParams")
    val authAthenzParams: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "authAthenzSecret")
    val authAthenzSecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "authTokenSecret")
    val authTokenSecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "connectionBackoff")
    val connectionBackoff: ArgoEventsBackoff? = null,

    /* Parameters is the list of parameters that is applied to resolved Kafka trigger object. */
    @SerialName(value = "parameters")
    val parameters: kotlin.collections.List<ArgoEventsTriggerParameter>? = null,

    /* Payload is the list of key-value extracted from an event payload to construct the request payload. */
    @SerialName(value = "payload")
    val payload: kotlin.collections.List<ArgoEventsTriggerParameter>? = null,

    @SerialName(value = "tls")
    val tls: ArgoEventsTLSConfig? = null,

    @SerialName(value = "tlsAllowInsecureConnection")
    val tlsAllowInsecureConnection: kotlin.Boolean? = null,

    @SerialName(value = "tlsTrustCertsSecret")
    val tlsTrustCertsSecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "tlsValidateHostname")
    val tlsValidateHostname: kotlin.Boolean? = null,

    @SerialName(value = "topic")
    val topic: kotlin.String? = null,

    @SerialName(value = "url")
    val url: kotlin.String? = null

) {


}

