/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsFileArtifact
import io.heapy.argo.client.models.ArgoEventsGitArtifact
import io.heapy.argo.client.models.ArgoEventsK8SResource
import io.heapy.argo.client.models.ArgoEventsS3Artifact
import io.heapy.argo.client.models.ArgoEventsURLArtifact
import io.heapy.argo.client.models.KubernetesConfigMapKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param configmap 
 * @param file 
 * @param git 
 * @param `inline` 
 * @param resource 
 * @param s3 
 * @param url 
 */
@Serializable

data class ArgoEventsArtifactLocation (

    @SerialName(value = "configmap")
    val configmap: KubernetesConfigMapKeySelector? = null,

    @SerialName(value = "file")
    val file: ArgoEventsFileArtifact? = null,

    @SerialName(value = "git")
    val git: ArgoEventsGitArtifact? = null,

    @SerialName(value = "inline")
    val `inline`: kotlin.String? = null,

    @SerialName(value = "resource")
    val resource: ArgoEventsK8SResource? = null,

    @SerialName(value = "s3")
    val s3: ArgoEventsS3Artifact? = null,

    @SerialName(value = "url")
    val url: ArgoEventsURLArtifact? = null

) {


}

