/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsCondition

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Status is a common structure which can be used for Status field.
 *
 * @param conditions 
 */
@Serializable

data class ArgoEventsStatus (

    @SerialName(value = "conditions")
    val conditions: kotlin.collections.List<ArgoEventsCondition>? = null

) {


}

