/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsS3Bucket
import io.heapy.argo.client.models.ArgoEventsS3Filter
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param accessKey 
 * @param bucket 
 * @param caCertificate 
 * @param endpoint 
 * @param events 
 * @param filter 
 * @param insecure 
 * @param metadata 
 * @param region 
 * @param secretKey 
 */
@Serializable

data class ArgoEventsS3Artifact (

    @SerialName(value = "accessKey")
    val accessKey: KubernetesSecretKeySelector? = null,

    @SerialName(value = "bucket")
    val bucket: ArgoEventsS3Bucket? = null,

    @SerialName(value = "caCertificate")
    val caCertificate: KubernetesSecretKeySelector? = null,

    @SerialName(value = "endpoint")
    val endpoint: kotlin.String? = null,

    @SerialName(value = "events")
    val events: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "filter")
    val filter: ArgoEventsS3Filter? = null,

    @SerialName(value = "insecure")
    val insecure: kotlin.Boolean? = null,

    @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "region")
    val region: kotlin.String? = null,

    @SerialName(value = "secretKey")
    val secretKey: KubernetesSecretKeySelector? = null

) {


}

