/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsTriggerParameter
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * CustomTrigger refers to the specification of the custom trigger.
 *
 * @param certSecret 
 * @param parameters Parameters is the list of parameters that is applied to resolved custom trigger trigger object.
 * @param payload Payload is the list of key-value extracted from an event payload to construct the request payload.
 * @param secure 
 * @param serverNameOverride ServerNameOverride for the secure connection between sensor and custom trigger gRPC server.
 * @param serverURL 
 * @param spec Spec is the custom trigger resource specification that custom trigger gRPC server knows how to interpret.
 */
@Serializable

data class ArgoEventsCustomTrigger (

    @SerialName(value = "certSecret")
    val certSecret: KubernetesSecretKeySelector? = null,

    /* Parameters is the list of parameters that is applied to resolved custom trigger trigger object. */
    @SerialName(value = "parameters")
    val parameters: kotlin.collections.List<ArgoEventsTriggerParameter>? = null,

    /* Payload is the list of key-value extracted from an event payload to construct the request payload. */
    @SerialName(value = "payload")
    val payload: kotlin.collections.List<ArgoEventsTriggerParameter>? = null,

    @SerialName(value = "secure")
    val secure: kotlin.Boolean? = null,

    /* ServerNameOverride for the secure connection between sensor and custom trigger gRPC server. */
    @SerialName(value = "serverNameOverride")
    val serverNameOverride: kotlin.String? = null,

    @SerialName(value = "serverURL")
    val serverURL: kotlin.String? = null,

    /* Spec is the custom trigger resource specification that custom trigger gRPC server knows how to interpret. */
    @SerialName(value = "spec")
    val spec: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

