/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsBasicAuth
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param basic 
 * @param credential 
 * @param nkey 
 * @param token 
 */
@Serializable

data class ArgoEventsNATSAuth (

    @SerialName(value = "basic")
    val basic: ArgoEventsBasicAuth? = null,

    @SerialName(value = "credential")
    val credential: KubernetesSecretKeySelector? = null,

    @SerialName(value = "nkey")
    val nkey: KubernetesSecretKeySelector? = null,

    @SerialName(value = "token")
    val token: KubernetesSecretKeySelector? = null

) {


}

