/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesConfigMapKeySelector
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param configMapKeyRef 
 * @param secretKeyRef 
 */
@Serializable

data class ArgoEventsValueFromSource (

    @SerialName(value = "configMapKeyRef")
    val configMapKeyRef: KubernetesConfigMapKeySelector? = null,

    @SerialName(value = "secretKeyRef")
    val secretKeyRef: KubernetesSecretKeySelector? = null

) {


}

