/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsEventSourceFilter
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param connectionString 
 * @param decodeMessage 
 * @param dlq 
 * @param filter 
 * @param jsonBody 
 * @param metadata 
 * @param queueName 
 * @param storageAccountName 
 * @param waitTimeInSeconds 
 */
@Serializable

data class ArgoEventsAzureQueueStorageEventSource (

    @SerialName(value = "connectionString")
    val connectionString: KubernetesSecretKeySelector? = null,

    @SerialName(value = "decodeMessage")
    val decodeMessage: kotlin.Boolean? = null,

    @SerialName(value = "dlq")
    val dlq: kotlin.Boolean? = null,

    @SerialName(value = "filter")
    val filter: ArgoEventsEventSourceFilter? = null,

    @SerialName(value = "jsonBody")
    val jsonBody: kotlin.Boolean? = null,

    @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "queueName")
    val queueName: kotlin.String? = null,

    @SerialName(value = "storageAccountName")
    val storageAccountName: kotlin.String? = null,

    @SerialName(value = "waitTimeInSeconds")
    val waitTimeInSeconds: kotlin.Int? = null

) {


}

