/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param projectKey ProjectKey is the key of project for which integration needs to set up.
 * @param repositorySlug RepositorySlug is the slug of the repository for which integration needs to set up.
 */
@Serializable

data class ArgoEventsBitbucketServerRepository (

    /* ProjectKey is the key of project for which integration needs to set up. */
    @SerialName(value = "projectKey")
    val projectKey: kotlin.String? = null,

    /* RepositorySlug is the slug of the repository for which integration needs to set up. */
    @SerialName(value = "repositorySlug")
    val repositorySlug: kotlin.String? = null

) {


}

