/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsPayloadField

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param expr Expr refers to the expression that determines the outcome of the filter.
 * @param fields Fields refers to set of keys that refer to the paths within event payload.
 */
@Serializable

data class ArgoEventsExprFilter (

    /* Expr refers to the expression that determines the outcome of the filter. */
    @SerialName(value = "expr")
    val expr: kotlin.String? = null,

    /* Fields refers to set of keys that refer to the paths within event payload. */
    @SerialName(value = "fields")
    val fields: kotlin.collections.List<ArgoEventsPayloadField>? = null

) {


}

