/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsAWSLambdaTrigger
import io.heapy.argo.client.models.ArgoEventsArgoWorkflowTrigger
import io.heapy.argo.client.models.ArgoEventsAzureEventHubsTrigger
import io.heapy.argo.client.models.ArgoEventsAzureServiceBusTrigger
import io.heapy.argo.client.models.ArgoEventsConditionsResetCriteria
import io.heapy.argo.client.models.ArgoEventsCustomTrigger
import io.heapy.argo.client.models.ArgoEventsEmailTrigger
import io.heapy.argo.client.models.ArgoEventsHTTPTrigger
import io.heapy.argo.client.models.ArgoEventsKafkaTrigger
import io.heapy.argo.client.models.ArgoEventsLogTrigger
import io.heapy.argo.client.models.ArgoEventsNATSTrigger
import io.heapy.argo.client.models.ArgoEventsOpenWhiskTrigger
import io.heapy.argo.client.models.ArgoEventsPulsarTrigger
import io.heapy.argo.client.models.ArgoEventsSlackTrigger
import io.heapy.argo.client.models.ArgoEventsStandardK8STrigger

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * TriggerTemplate is the template that describes trigger specification.
 *
 * @param argoWorkflow 
 * @param awsLambda 
 * @param azureEventHubs 
 * @param azureServiceBus 
 * @param conditions 
 * @param conditionsReset 
 * @param custom 
 * @param email 
 * @param http 
 * @param k8s 
 * @param kafka 
 * @param log 
 * @param name Name is a unique name of the action to take.
 * @param nats 
 * @param openWhisk 
 * @param pulsar 
 * @param slack 
 */
@Serializable

data class ArgoEventsTriggerTemplate (

    @SerialName(value = "argoWorkflow")
    val argoWorkflow: ArgoEventsArgoWorkflowTrigger? = null,

    @SerialName(value = "awsLambda")
    val awsLambda: ArgoEventsAWSLambdaTrigger? = null,

    @SerialName(value = "azureEventHubs")
    val azureEventHubs: ArgoEventsAzureEventHubsTrigger? = null,

    @SerialName(value = "azureServiceBus")
    val azureServiceBus: ArgoEventsAzureServiceBusTrigger? = null,

    @SerialName(value = "conditions")
    val conditions: kotlin.String? = null,

    @SerialName(value = "conditionsReset")
    val conditionsReset: kotlin.collections.List<ArgoEventsConditionsResetCriteria>? = null,

    @SerialName(value = "custom")
    val custom: ArgoEventsCustomTrigger? = null,

    @SerialName(value = "email")
    val email: ArgoEventsEmailTrigger? = null,

    @SerialName(value = "http")
    val http: ArgoEventsHTTPTrigger? = null,

    @SerialName(value = "k8s")
    val k8s: ArgoEventsStandardK8STrigger? = null,

    @SerialName(value = "kafka")
    val kafka: ArgoEventsKafkaTrigger? = null,

    @SerialName(value = "log")
    val log: ArgoEventsLogTrigger? = null,

    /* Name is a unique name of the action to take. */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "nats")
    val nats: ArgoEventsNATSTrigger? = null,

    @SerialName(value = "openWhisk")
    val openWhisk: ArgoEventsOpenWhiskTrigger? = null,

    @SerialName(value = "pulsar")
    val pulsar: ArgoEventsPulsarTrigger? = null,

    @SerialName(value = "slack")
    val slack: ArgoEventsSlackTrigger? = null

) {


}

