/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * TLSConfig refers to TLS configuration for a client.
 *
 * @param caCertSecret 
 * @param clientCertSecret 
 * @param clientKeySecret 
 * @param insecureSkipVerify 
 */
@Serializable

data class ArgoEventsTLSConfig (

    @SerialName(value = "caCertSecret")
    val caCertSecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "clientCertSecret")
    val clientCertSecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "clientKeySecret")
    val clientKeySecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "insecureSkipVerify")
    val insecureSkipVerify: kotlin.Boolean? = null

) {


}

