/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsNATSAuth
import io.heapy.argo.client.models.ArgoEventsTLSConfig
import io.heapy.argo.client.models.ArgoEventsTriggerParameter

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * NATSTrigger refers to the specification of the NATS trigger.
 *
 * @param auth 
 * @param parameters 
 * @param payload 
 * @param subject Name of the subject to put message on.
 * @param tls 
 * @param url URL of the NATS cluster.
 */
@Serializable

data class ArgoEventsNATSTrigger (

    @SerialName(value = "auth")
    val auth: ArgoEventsNATSAuth? = null,

    @SerialName(value = "parameters")
    val parameters: kotlin.collections.List<ArgoEventsTriggerParameter>? = null,

    @SerialName(value = "payload")
    val payload: kotlin.collections.List<ArgoEventsTriggerParameter>? = null,

    /* Name of the subject to put message on. */
    @SerialName(value = "subject")
    val subject: kotlin.String? = null,

    @SerialName(value = "tls")
    val tls: ArgoEventsTLSConfig? = null,

    /* URL of the NATS cluster. */
    @SerialName(value = "url")
    val url: kotlin.String? = null

) {


}

