/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsBasicAuth
import io.heapy.argo.client.models.ArgoEventsSecureHeader
import io.heapy.argo.client.models.ArgoEventsTLSConfig
import io.heapy.argo.client.models.ArgoEventsTriggerParameter

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param basicAuth 
 * @param headers 
 * @param method 
 * @param parameters Parameters is the list of key-value extracted from event's payload that are applied to the HTTP trigger resource.
 * @param payload 
 * @param secureHeaders 
 * @param timeout 
 * @param tls 
 * @param url URL refers to the URL to send HTTP request to.
 */
@Serializable

data class ArgoEventsHTTPTrigger (

    @SerialName(value = "basicAuth")
    val basicAuth: ArgoEventsBasicAuth? = null,

    @SerialName(value = "headers")
    val headers: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "method")
    val method: kotlin.String? = null,

    /* Parameters is the list of key-value extracted from event's payload that are applied to the HTTP trigger resource. */
    @SerialName(value = "parameters")
    val parameters: kotlin.collections.List<ArgoEventsTriggerParameter>? = null,

    @SerialName(value = "payload")
    val payload: kotlin.collections.List<ArgoEventsTriggerParameter>? = null,

    @SerialName(value = "secureHeaders")
    val secureHeaders: kotlin.collections.List<ArgoEventsSecureHeader>? = null,

    @SerialName(value = "timeout")
    val timeout: kotlin.String? = null,

    @SerialName(value = "tls")
    val tls: ArgoEventsTLSConfig? = null,

    /* URL refers to the URL to send HTTP request to. */
    @SerialName(value = "url")
    val url: kotlin.String? = null

) {


}

