/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsArtifactLocation
import io.heapy.argo.client.models.ArgoEventsTriggerParameter

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param args 
 * @param operation 
 * @param parameters 
 * @param source 
 */
@Serializable

data class ArgoEventsArgoWorkflowTrigger (

    @SerialName(value = "args")
    val args: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "operation")
    val operation: kotlin.String? = null,

    @SerialName(value = "parameters")
    val parameters: kotlin.collections.List<ArgoEventsTriggerParameter>? = null,

    @SerialName(value = "source")
    val source: ArgoEventsArtifactLocation? = null

) {


}

