/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsEventSourceFilter
import io.heapy.argo.client.models.ArgoEventsWebhookContext

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param filter 
 * @param webhookContext 
 */
@Serializable

data class ArgoEventsWebhookEventSource (

    @SerialName(value = "filter")
    val filter: ArgoEventsEventSourceFilter? = null,

    @SerialName(value = "webhookContext")
    val webhookContext: ArgoEventsWebhookContext? = null

) {


}

