/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param annotations 
 * @param labels 
 */
@Serializable

data class ArgoEventsMetadata (

    @SerialName(value = "annotations")
    val annotations: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "labels")
    val labels: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

