/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsEventSourceFilter
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param accessKey 
 * @param dlq 
 * @param endpoint 
 * @param filter 
 * @param jsonBody 
 * @param metadata 
 * @param queue 
 * @param queueAccountId 
 * @param region 
 * @param roleARN 
 * @param secretKey 
 * @param sessionToken 
 * @param waitTimeSeconds WaitTimeSeconds is The duration (in seconds) for which the call waits for a message to arrive in the queue before returning.
 */
@Serializable

data class ArgoEventsSQSEventSource (

    @SerialName(value = "accessKey")
    val accessKey: KubernetesSecretKeySelector? = null,

    @SerialName(value = "dlq")
    val dlq: kotlin.Boolean? = null,

    @SerialName(value = "endpoint")
    val endpoint: kotlin.String? = null,

    @SerialName(value = "filter")
    val filter: ArgoEventsEventSourceFilter? = null,

    @SerialName(value = "jsonBody")
    val jsonBody: kotlin.Boolean? = null,

    @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "queue")
    val queue: kotlin.String? = null,

    @SerialName(value = "queueAccountId")
    val queueAccountId: kotlin.String? = null,

    @SerialName(value = "region")
    val region: kotlin.String? = null,

    @SerialName(value = "roleARN")
    val roleARN: kotlin.String? = null,

    @SerialName(value = "secretKey")
    val secretKey: KubernetesSecretKeySelector? = null,

    @SerialName(value = "sessionToken")
    val sessionToken: KubernetesSecretKeySelector? = null,

    /* WaitTimeSeconds is The duration (in seconds) for which the call waits for a message to arrive in the queue before returning. */
    @SerialName(value = "waitTimeSeconds")
    val waitTimeSeconds: kotlin.String? = null

) {


}

