/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param autoDelete 
 * @param durable 
 * @param `internal` 
 * @param noWait 
 */
@Serializable

data class ArgoEventsAMQPExchangeDeclareConfig (

    @SerialName(value = "autoDelete")
    val autoDelete: kotlin.Boolean? = null,

    @SerialName(value = "durable")
    val durable: kotlin.Boolean? = null,

    @SerialName(value = "internal")
    val `internal`: kotlin.Boolean? = null,

    @SerialName(value = "noWait")
    val noWait: kotlin.Boolean? = null

) {


}

