/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsArtifactLocation
import io.heapy.argo.client.models.ArgoEventsTriggerParameter

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param liveObject 
 * @param operation 
 * @param parameters Parameters is the list of parameters that is applied to resolved K8s trigger object.
 * @param patchStrategy 
 * @param source 
 */
@Serializable

data class ArgoEventsStandardK8STrigger (

    @SerialName(value = "liveObject")
    val liveObject: kotlin.Boolean? = null,

    @SerialName(value = "operation")
    val operation: kotlin.String? = null,

    /* Parameters is the list of parameters that is applied to resolved K8s trigger object. */
    @SerialName(value = "parameters")
    val parameters: kotlin.collections.List<ArgoEventsTriggerParameter>? = null,

    @SerialName(value = "patchStrategy")
    val patchStrategy: kotlin.String? = null,

    @SerialName(value = "source")
    val source: ArgoEventsArtifactLocation? = null

) {


}

