/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param autoAck 
 * @param consumerTag 
 * @param exclusive 
 * @param noLocal 
 * @param noWait 
 */
@Serializable

data class ArgoEventsAMQPConsumeConfig (

    @SerialName(value = "autoAck")
    val autoAck: kotlin.Boolean? = null,

    @SerialName(value = "consumerTag")
    val consumerTag: kotlin.String? = null,

    @SerialName(value = "exclusive")
    val exclusive: kotlin.Boolean? = null,

    @SerialName(value = "noLocal")
    val noLocal: kotlin.Boolean? = null,

    @SerialName(value = "noWait")
    val noWait: kotlin.Boolean? = null

) {


}

