/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsBackoff
import io.heapy.argo.client.models.ArgoEventsBasicAuth
import io.heapy.argo.client.models.ArgoEventsEventSourceFilter
import io.heapy.argo.client.models.ArgoEventsTLSConfig

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param auth 
 * @param clientId 
 * @param connectionBackoff 
 * @param filter 
 * @param jsonBody 
 * @param metadata 
 * @param tls 
 * @param topic 
 * @param url 
 */
@Serializable

data class ArgoEventsMQTTEventSource (

    @SerialName(value = "auth")
    val auth: ArgoEventsBasicAuth? = null,

    @SerialName(value = "clientId")
    val clientId: kotlin.String? = null,

    @SerialName(value = "connectionBackoff")
    val connectionBackoff: ArgoEventsBackoff? = null,

    @SerialName(value = "filter")
    val filter: ArgoEventsEventSourceFilter? = null,

    @SerialName(value = "jsonBody")
    val jsonBody: kotlin.Boolean? = null,

    @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "tls")
    val tls: ArgoEventsTLSConfig? = null,

    @SerialName(value = "topic")
    val topic: kotlin.String? = null,

    @SerialName(value = "url")
    val url: kotlin.String? = null

) {


}

