/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsTLSConfig
import io.heapy.argo.client.models.ArgoEventsTriggerParameter
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param connectionString 
 * @param parameters 
 * @param payload Payload is the list of key-value extracted from an event payload to construct the request payload.
 * @param queueName 
 * @param subscriptionName 
 * @param tls 
 * @param topicName 
 */
@Serializable

data class ArgoEventsAzureServiceBusTrigger (

    @SerialName(value = "connectionString")
    val connectionString: KubernetesSecretKeySelector? = null,

    @SerialName(value = "parameters")
    val parameters: kotlin.collections.List<ArgoEventsTriggerParameter>? = null,

    /* Payload is the list of key-value extracted from an event payload to construct the request payload. */
    @SerialName(value = "payload")
    val payload: kotlin.collections.List<ArgoEventsTriggerParameter>? = null,

    @SerialName(value = "queueName")
    val queueName: kotlin.String? = null,

    @SerialName(value = "subscriptionName")
    val subscriptionName: kotlin.String? = null,

    @SerialName(value = "tls")
    val tls: ArgoEventsTLSConfig? = null,

    @SerialName(value = "topicName")
    val topicName: kotlin.String? = null

) {


}

