/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param icon 
 * @param username 
 */
@Serializable

data class ArgoEventsSlackSender (

    @SerialName(value = "icon")
    val icon: kotlin.String? = null,

    @SerialName(value = "username")
    val username: kotlin.String? = null

) {


}

