/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsBasicAuth
import io.heapy.argo.client.models.ArgoEventsEventSourceFilter
import io.heapy.argo.client.models.ArgoEventsWebhookContext

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param auth 
 * @param deleteHookOnFinish 
 * @param events 
 * @param filter 
 * @param gerritBaseURL 
 * @param hookName 
 * @param metadata 
 * @param projects List of project namespace paths like \"whynowy/test\".
 * @param sslVerify 
 * @param webhook 
 */
@Serializable

data class ArgoEventsGerritEventSource (

    @SerialName(value = "auth")
    val auth: ArgoEventsBasicAuth? = null,

    @SerialName(value = "deleteHookOnFinish")
    val deleteHookOnFinish: kotlin.Boolean? = null,

    @SerialName(value = "events")
    val events: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "filter")
    val filter: ArgoEventsEventSourceFilter? = null,

    @SerialName(value = "gerritBaseURL")
    val gerritBaseURL: kotlin.String? = null,

    @SerialName(value = "hookName")
    val hookName: kotlin.String? = null,

    @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* List of project namespace paths like \"whynowy/test\". */
    @SerialName(value = "projects")
    val projects: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "sslVerify")
    val sslVerify: kotlin.Boolean? = null,

    @SerialName(value = "webhook")
    val webhook: ArgoEventsWebhookContext? = null

) {


}

