/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param jq 
 * @param script 
 */
@Serializable

data class ArgoEventsEventDependencyTransformer (

    @SerialName(value = "jq")
    val jq: kotlin.String? = null,

    @SerialName(value = "script")
    val script: kotlin.String? = null

) {


}

