/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsEventSourceFilter
import io.heapy.argo.client.models.ArgoEventsWatchPathConfig
import io.heapy.argo.client.models.KubernetesConfigMapKeySelector
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param addresses 
 * @param checkInterval 
 * @param filter 
 * @param hdfsUser HDFSUser is the user to access HDFS file system. It is ignored if either ccache or keytab is used.
 * @param krbCCacheSecret 
 * @param krbConfigConfigMap 
 * @param krbKeytabSecret 
 * @param krbRealm KrbRealm is the Kerberos realm used with Kerberos keytab It must be set if keytab is used.
 * @param krbServicePrincipalName KrbServicePrincipalName is the principal name of Kerberos service It must be set if either ccache or keytab is used.
 * @param krbUsername KrbUsername is the Kerberos username used with Kerberos keytab It must be set if keytab is used.
 * @param metadata 
 * @param type 
 * @param watchPathConfig 
 */
@Serializable

data class ArgoEventsHDFSEventSource (

    @SerialName(value = "addresses")
    val addresses: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "checkInterval")
    val checkInterval: kotlin.String? = null,

    @SerialName(value = "filter")
    val filter: ArgoEventsEventSourceFilter? = null,

    /* HDFSUser is the user to access HDFS file system. It is ignored if either ccache or keytab is used. */
    @SerialName(value = "hdfsUser")
    val hdfsUser: kotlin.String? = null,

    @SerialName(value = "krbCCacheSecret")
    val krbCCacheSecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "krbConfigConfigMap")
    val krbConfigConfigMap: KubernetesConfigMapKeySelector? = null,

    @SerialName(value = "krbKeytabSecret")
    val krbKeytabSecret: KubernetesSecretKeySelector? = null,

    /* KrbRealm is the Kerberos realm used with Kerberos keytab It must be set if keytab is used. */
    @SerialName(value = "krbRealm")
    val krbRealm: kotlin.String? = null,

    /* KrbServicePrincipalName is the principal name of Kerberos service It must be set if either ccache or keytab is used. */
    @SerialName(value = "krbServicePrincipalName")
    val krbServicePrincipalName: kotlin.String? = null,

    /* KrbUsername is the Kerberos username used with Kerberos keytab It must be set if keytab is used. */
    @SerialName(value = "krbUsername")
    val krbUsername: kotlin.String? = null,

    @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "type")
    val type: kotlin.String? = null,

    @SerialName(value = "watchPathConfig")
    val watchPathConfig: ArgoEventsWatchPathConfig? = null

) {


}

