/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsBasicAuth

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param auth 
 * @param schemaId 
 * @param url Schema Registry URL.
 */
@Serializable

data class ArgoEventsSchemaRegistryConfig (

    @SerialName(value = "auth")
    val auth: ArgoEventsBasicAuth? = null,

    @SerialName(value = "schemaId")
    val schemaId: kotlin.Int? = null,

    /* Schema Registry URL. */
    @SerialName(value = "url")
    val url: kotlin.String? = null

) {


}

