/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsBackoff
import io.heapy.argo.client.models.ArgoEventsEventSourceFilter
import io.heapy.argo.client.models.ArgoEventsTLSConfig
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param broker Broker URI to connect to.
 * @param channelKey 
 * @param channelName 
 * @param connectionBackoff 
 * @param filter 
 * @param jsonBody 
 * @param metadata 
 * @param password 
 * @param tls 
 * @param username 
 */
@Serializable

data class ArgoEventsEmitterEventSource (

    /* Broker URI to connect to. */
    @SerialName(value = "broker")
    val broker: kotlin.String? = null,

    @SerialName(value = "channelKey")
    val channelKey: kotlin.String? = null,

    @SerialName(value = "channelName")
    val channelName: kotlin.String? = null,

    @SerialName(value = "connectionBackoff")
    val connectionBackoff: ArgoEventsBackoff? = null,

    @SerialName(value = "filter")
    val filter: ArgoEventsEventSourceFilter? = null,

    @SerialName(value = "jsonBody")
    val jsonBody: kotlin.Boolean? = null,

    @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "password")
    val password: KubernetesSecretKeySelector? = null,

    @SerialName(value = "tls")
    val tls: ArgoEventsTLSConfig? = null,

    @SerialName(value = "username")
    val username: KubernetesSecretKeySelector? = null

) {


}

