/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param authSecret 
 * @param endpoint 
 * @param maxPayloadSize 
 * @param metadata 
 * @param method 
 * @param port Port on which HTTP server is listening for incoming events.
 * @param serverCertSecret 
 * @param serverKeySecret 
 * @param url URL is the url of the server.
 */
@Serializable

data class ArgoEventsWebhookContext (

    @SerialName(value = "authSecret")
    val authSecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "endpoint")
    val endpoint: kotlin.String? = null,

    @SerialName(value = "maxPayloadSize")
    val maxPayloadSize: kotlin.String? = null,

    @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "method")
    val method: kotlin.String? = null,

    /* Port on which HTTP server is listening for incoming events. */
    @SerialName(value = "port")
    val port: kotlin.String? = null,

    @SerialName(value = "serverCertSecret")
    val serverCertSecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "serverKeySecret")
    val serverKeySecret: KubernetesSecretKeySelector? = null,

    /* URL is the url of the server. */
    @SerialName(value = "url")
    val url: kotlin.String? = null

) {


}

