/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesEnvFromSource
import io.heapy.argo.client.models.KubernetesEnvVar
import io.heapy.argo.client.models.KubernetesResourceRequirements
import io.heapy.argo.client.models.KubernetesSecurityContext
import io.heapy.argo.client.models.KubernetesVolumeMount

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param env 
 * @param envFrom 
 * @param imagePullPolicy 
 * @param resources 
 * @param securityContext 
 * @param volumeMounts 
 */
@Serializable

data class ArgoEventsContainer (

    @SerialName(value = "env")
    val env: kotlin.collections.List<KubernetesEnvVar>? = null,

    @SerialName(value = "envFrom")
    val envFrom: kotlin.collections.List<KubernetesEnvFromSource>? = null,

    @SerialName(value = "imagePullPolicy")
    val imagePullPolicy: kotlin.String? = null,

    @SerialName(value = "resources")
    val resources: KubernetesResourceRequirements? = null,

    @SerialName(value = "securityContext")
    val securityContext: KubernetesSecurityContext? = null,

    @SerialName(value = "volumeMounts")
    val volumeMounts: kotlin.collections.List<KubernetesVolumeMount>? = null

) {


}

