/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsEventSourceFilter
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * GenericEventSource refers to a generic event source. It can be used to implement a custom event source.
 *
 * @param authSecret 
 * @param config 
 * @param filter 
 * @param insecure Insecure determines the type of connection.
 * @param jsonBody 
 * @param metadata 
 * @param url URL of the gRPC server that implements the event source.
 */
@Serializable

data class ArgoEventsGenericEventSource (

    @SerialName(value = "authSecret")
    val authSecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "config")
    val config: kotlin.String? = null,

    @SerialName(value = "filter")
    val filter: ArgoEventsEventSourceFilter? = null,

    /* Insecure determines the type of connection. */
    @SerialName(value = "insecure")
    val insecure: kotlin.Boolean? = null,

    @SerialName(value = "jsonBody")
    val jsonBody: kotlin.Boolean? = null,

    @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* URL of the gRPC server that implements the event source. */
    @SerialName(value = "url")
    val url: kotlin.String? = null

) {


}

