/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Selector represents conditional operation to select K8s objects.
 *
 * @param key 
 * @param operation 
 * @param `value` 
 */
@Serializable

data class ArgoEventsSelector (

    @SerialName(value = "key")
    val key: kotlin.String? = null,

    @SerialName(value = "operation")
    val operation: kotlin.String? = null,

    @SerialName(value = "value")
    val `value`: kotlin.String? = null

) {


}

