/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsEventPersistence
import io.heapy.argo.client.models.ArgoEventsEventSourceFilter

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param exclusionDates ExclusionDates defines the list of DATE-TIME exceptions for recurring events.
 * @param filter 
 * @param interval 
 * @param metadata 
 * @param persistence 
 * @param schedule 
 * @param timezone 
 */
@Serializable

data class ArgoEventsCalendarEventSource (

    /* ExclusionDates defines the list of DATE-TIME exceptions for recurring events. */
    @SerialName(value = "exclusionDates")
    val exclusionDates: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "filter")
    val filter: ArgoEventsEventSourceFilter? = null,

    @SerialName(value = "interval")
    val interval: kotlin.String? = null,

    @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "persistence")
    val persistence: ArgoEventsEventPersistence? = null,

    @SerialName(value = "schedule")
    val schedule: kotlin.String? = null,

    @SerialName(value = "timezone")
    val timezone: kotlin.String? = null

) {


}

