/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param broadcastMessageToChannel 
 * @param messageAggregationKey 
 */
@Serializable

data class ArgoEventsSlackThread (

    @SerialName(value = "broadcastMessageToChannel")
    val broadcastMessageToChannel: kotlin.Boolean? = null,

    @SerialName(value = "messageAggregationKey")
    val messageAggregationKey: kotlin.String? = null

) {


}

