/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsEventSourceFilter
import io.heapy.argo.client.models.ArgoEventsTLSConfig
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param consumerGroup 
 * @param db 
 * @param filter 
 * @param hostAddress 
 * @param maxMsgCountPerRead 
 * @param metadata 
 * @param password 
 * @param streams Streams to look for entries. XREADGROUP is used on all streams using a single consumer group.
 * @param tls 
 * @param username 
 */
@Serializable

data class ArgoEventsRedisStreamEventSource (

    @SerialName(value = "consumerGroup")
    val consumerGroup: kotlin.String? = null,

    @SerialName(value = "db")
    val db: kotlin.Int? = null,

    @SerialName(value = "filter")
    val filter: ArgoEventsEventSourceFilter? = null,

    @SerialName(value = "hostAddress")
    val hostAddress: kotlin.String? = null,

    @SerialName(value = "maxMsgCountPerRead")
    val maxMsgCountPerRead: kotlin.Int? = null,

    @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "password")
    val password: KubernetesSecretKeySelector? = null,

    /* Streams to look for entries. XREADGROUP is used on all streams using a single consumer group. */
    @SerialName(value = "streams")
    val streams: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "tls")
    val tls: ArgoEventsTLSConfig? = null,

    @SerialName(value = "username")
    val username: kotlin.String? = null

) {


}

