/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param arguments 
 * @param autoDelete 
 * @param durable 
 * @param exclusive 
 * @param name 
 * @param noWait 
 */
@Serializable

data class ArgoEventsAMQPQueueDeclareConfig (

    @SerialName(value = "arguments")
    val arguments: kotlin.String? = null,

    @SerialName(value = "autoDelete")
    val autoDelete: kotlin.Boolean? = null,

    @SerialName(value = "durable")
    val durable: kotlin.Boolean? = null,

    @SerialName(value = "exclusive")
    val exclusive: kotlin.Boolean? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "noWait")
    val noWait: kotlin.Boolean? = null

) {


}

