/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsWebhookContext
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param apiKey 
 * @param createWebhook 
 * @param eventFilter 
 * @param metadata 
 * @param webhook 
 */
@Serializable

data class ArgoEventsStripeEventSource (

    @SerialName(value = "apiKey")
    val apiKey: KubernetesSecretKeySelector? = null,

    @SerialName(value = "createWebhook")
    val createWebhook: kotlin.Boolean? = null,

    @SerialName(value = "eventFilter")
    val eventFilter: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "webhook")
    val webhook: ArgoEventsWebhookContext? = null

) {


}

