/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsBackoff
import io.heapy.argo.client.models.ArgoEventsEventSourceFilter
import io.heapy.argo.client.models.ArgoEventsTLSConfig
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param authAthenzParams 
 * @param authAthenzSecret 
 * @param authTokenSecret 
 * @param connectionBackoff 
 * @param filter 
 * @param jsonBody 
 * @param metadata 
 * @param tls 
 * @param tlsAllowInsecureConnection 
 * @param tlsTrustCertsSecret 
 * @param tlsValidateHostname 
 * @param topics 
 * @param type 
 * @param url 
 */
@Serializable

data class ArgoEventsPulsarEventSource (

    @SerialName(value = "authAthenzParams")
    val authAthenzParams: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "authAthenzSecret")
    val authAthenzSecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "authTokenSecret")
    val authTokenSecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "connectionBackoff")
    val connectionBackoff: ArgoEventsBackoff? = null,

    @SerialName(value = "filter")
    val filter: ArgoEventsEventSourceFilter? = null,

    @SerialName(value = "jsonBody")
    val jsonBody: kotlin.Boolean? = null,

    @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "tls")
    val tls: ArgoEventsTLSConfig? = null,

    @SerialName(value = "tlsAllowInsecureConnection")
    val tlsAllowInsecureConnection: kotlin.Boolean? = null,

    @SerialName(value = "tlsTrustCertsSecret")
    val tlsTrustCertsSecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "tlsValidateHostname")
    val tlsValidateHostname: kotlin.Boolean? = null,

    @SerialName(value = "topics")
    val topics: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "type")
    val type: kotlin.String? = null,

    @SerialName(value = "url")
    val url: kotlin.String? = null

) {


}

