/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param owner 
 * @param repositorySlug 
 */
@Serializable

data class ArgoEventsBitbucketRepository (

    @SerialName(value = "owner")
    val owner: kotlin.String? = null,

    @SerialName(value = "repositorySlug")
    val repositorySlug: kotlin.String? = null

) {


}

