/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsBackoff
import io.heapy.argo.client.models.ArgoEventsEventSourceFilter
import io.heapy.argo.client.models.ArgoEventsNATSAuth
import io.heapy.argo.client.models.ArgoEventsTLSConfig

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param auth 
 * @param connectionBackoff 
 * @param filter 
 * @param jsonBody 
 * @param metadata 
 * @param queue 
 * @param subject 
 * @param tls 
 * @param url 
 */
@Serializable

data class ArgoEventsNATSEventsSource (

    @SerialName(value = "auth")
    val auth: ArgoEventsNATSAuth? = null,

    @SerialName(value = "connectionBackoff")
    val connectionBackoff: ArgoEventsBackoff? = null,

    @SerialName(value = "filter")
    val filter: ArgoEventsEventSourceFilter? = null,

    @SerialName(value = "jsonBody")
    val jsonBody: kotlin.Boolean? = null,

    @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "queue")
    val queue: kotlin.String? = null,

    @SerialName(value = "subject")
    val subject: kotlin.String? = null,

    @SerialName(value = "tls")
    val tls: ArgoEventsTLSConfig? = null,

    @SerialName(value = "url")
    val url: kotlin.String? = null

) {


}

