/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param appID 
 * @param installationID 
 * @param privateKey 
 */
@Serializable

data class ArgoEventsGithubAppCreds (

    @SerialName(value = "appID")
    val appID: kotlin.String? = null,

    @SerialName(value = "installationID")
    val installationID: kotlin.String? = null,

    @SerialName(value = "privateKey")
    val privateKey: KubernetesSecretKeySelector? = null

) {


}

