/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsBitbucketBasicAuth
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param basic 
 * @param oauthToken 
 */
@Serializable

data class ArgoEventsBitbucketAuth (

    @SerialName(value = "basic")
    val basic: ArgoEventsBitbucketBasicAuth? = null,

    @SerialName(value = "oauthToken")
    val oauthToken: KubernetesSecretKeySelector? = null

) {


}

