/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * URLArtifact contains information about an artifact at an http endpoint.
 *
 * @param path 
 * @param verifyCert 
 */
@Serializable

data class ArgoEventsURLArtifact (

    @SerialName(value = "path")
    val path: kotlin.String? = null,

    @SerialName(value = "verifyCert")
    val verifyCert: kotlin.Boolean? = null

) {


}

