/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsSelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlin.time.Instant

/**
 * 
 *
 * @param afterStart 
 * @param createdBy Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
 * @param fields 
 * @param labels 
 * @param prefix 
 */
@Serializable

data class ArgoEventsResourceFilter (

    @SerialName(value = "afterStart")
    val afterStart: kotlin.Boolean? = null,

    /* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. */
    @Contextual @SerialName(value = "createdBy")
    val createdBy: Instant? = null,

    @SerialName(value = "fields")
    val fields: kotlin.collections.List<ArgoEventsSelector>? = null,

    @SerialName(value = "labels")
    val labels: kotlin.collections.List<ArgoEventsSelector>? = null,

    @SerialName(value = "prefix")
    val prefix: kotlin.String? = null

) {


}

