/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsAMQPEventSource
import io.heapy.argo.client.models.ArgoEventsAzureEventsHubEventSource
import io.heapy.argo.client.models.ArgoEventsAzureQueueStorageEventSource
import io.heapy.argo.client.models.ArgoEventsAzureServiceBusEventSource
import io.heapy.argo.client.models.ArgoEventsBitbucketEventSource
import io.heapy.argo.client.models.ArgoEventsBitbucketServerEventSource
import io.heapy.argo.client.models.ArgoEventsCalendarEventSource
import io.heapy.argo.client.models.ArgoEventsEmitterEventSource
import io.heapy.argo.client.models.ArgoEventsFileEventSource
import io.heapy.argo.client.models.ArgoEventsGenericEventSource
import io.heapy.argo.client.models.ArgoEventsGerritEventSource
import io.heapy.argo.client.models.ArgoEventsGithubEventSource
import io.heapy.argo.client.models.ArgoEventsGitlabEventSource
import io.heapy.argo.client.models.ArgoEventsHDFSEventSource
import io.heapy.argo.client.models.ArgoEventsKafkaEventSource
import io.heapy.argo.client.models.ArgoEventsMQTTEventSource
import io.heapy.argo.client.models.ArgoEventsNATSEventsSource
import io.heapy.argo.client.models.ArgoEventsNSQEventSource
import io.heapy.argo.client.models.ArgoEventsPubSubEventSource
import io.heapy.argo.client.models.ArgoEventsPulsarEventSource
import io.heapy.argo.client.models.ArgoEventsRedisEventSource
import io.heapy.argo.client.models.ArgoEventsRedisStreamEventSource
import io.heapy.argo.client.models.ArgoEventsResourceEventSource
import io.heapy.argo.client.models.ArgoEventsS3Artifact
import io.heapy.argo.client.models.ArgoEventsSFTPEventSource
import io.heapy.argo.client.models.ArgoEventsSNSEventSource
import io.heapy.argo.client.models.ArgoEventsSQSEventSource
import io.heapy.argo.client.models.ArgoEventsService
import io.heapy.argo.client.models.ArgoEventsSlackEventSource
import io.heapy.argo.client.models.ArgoEventsStorageGridEventSource
import io.heapy.argo.client.models.ArgoEventsStripeEventSource
import io.heapy.argo.client.models.ArgoEventsTemplate
import io.heapy.argo.client.models.ArgoEventsWebhookEventSource

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param amqp 
 * @param azureEventsHub 
 * @param azureQueueStorage 
 * @param azureServiceBus 
 * @param bitbucket 
 * @param bitbucketserver 
 * @param calendar 
 * @param emitter 
 * @param eventBusName 
 * @param file 
 * @param generic 
 * @param gerrit 
 * @param github 
 * @param gitlab 
 * @param hdfs 
 * @param kafka 
 * @param minio 
 * @param mqtt 
 * @param nats 
 * @param nsq 
 * @param pubSub 
 * @param pulsar 
 * @param redis 
 * @param redisStream 
 * @param replicas 
 * @param resource 
 * @param service 
 * @param sftp 
 * @param slack 
 * @param sns 
 * @param sqs 
 * @param storageGrid 
 * @param stripe 
 * @param template 
 * @param webhook 
 */
@Serializable

data class ArgoEventsEventSourceSpec (

    @Contextual @SerialName(value = "amqp")
    val amqp: kotlin.collections.Map<kotlin.String, ArgoEventsAMQPEventSource>? = null,

    @Contextual @SerialName(value = "azureEventsHub")
    val azureEventsHub: kotlin.collections.Map<kotlin.String, ArgoEventsAzureEventsHubEventSource>? = null,

    @Contextual @SerialName(value = "azureQueueStorage")
    val azureQueueStorage: kotlin.collections.Map<kotlin.String, ArgoEventsAzureQueueStorageEventSource>? = null,

    @Contextual @SerialName(value = "azureServiceBus")
    val azureServiceBus: kotlin.collections.Map<kotlin.String, ArgoEventsAzureServiceBusEventSource>? = null,

    @Contextual @SerialName(value = "bitbucket")
    val bitbucket: kotlin.collections.Map<kotlin.String, ArgoEventsBitbucketEventSource>? = null,

    @Contextual @SerialName(value = "bitbucketserver")
    val bitbucketserver: kotlin.collections.Map<kotlin.String, ArgoEventsBitbucketServerEventSource>? = null,

    @Contextual @SerialName(value = "calendar")
    val calendar: kotlin.collections.Map<kotlin.String, ArgoEventsCalendarEventSource>? = null,

    @Contextual @SerialName(value = "emitter")
    val emitter: kotlin.collections.Map<kotlin.String, ArgoEventsEmitterEventSource>? = null,

    @SerialName(value = "eventBusName")
    val eventBusName: kotlin.String? = null,

    @Contextual @SerialName(value = "file")
    val file: kotlin.collections.Map<kotlin.String, ArgoEventsFileEventSource>? = null,

    @Contextual @SerialName(value = "generic")
    val generic: kotlin.collections.Map<kotlin.String, ArgoEventsGenericEventSource>? = null,

    @Contextual @SerialName(value = "gerrit")
    val gerrit: kotlin.collections.Map<kotlin.String, ArgoEventsGerritEventSource>? = null,

    @Contextual @SerialName(value = "github")
    val github: kotlin.collections.Map<kotlin.String, ArgoEventsGithubEventSource>? = null,

    @Contextual @SerialName(value = "gitlab")
    val gitlab: kotlin.collections.Map<kotlin.String, ArgoEventsGitlabEventSource>? = null,

    @Contextual @SerialName(value = "hdfs")
    val hdfs: kotlin.collections.Map<kotlin.String, ArgoEventsHDFSEventSource>? = null,

    @Contextual @SerialName(value = "kafka")
    val kafka: kotlin.collections.Map<kotlin.String, ArgoEventsKafkaEventSource>? = null,

    @Contextual @SerialName(value = "minio")
    val minio: kotlin.collections.Map<kotlin.String, ArgoEventsS3Artifact>? = null,

    @Contextual @SerialName(value = "mqtt")
    val mqtt: kotlin.collections.Map<kotlin.String, ArgoEventsMQTTEventSource>? = null,

    @Contextual @SerialName(value = "nats")
    val nats: kotlin.collections.Map<kotlin.String, ArgoEventsNATSEventsSource>? = null,

    @Contextual @SerialName(value = "nsq")
    val nsq: kotlin.collections.Map<kotlin.String, ArgoEventsNSQEventSource>? = null,

    @Contextual @SerialName(value = "pubSub")
    val pubSub: kotlin.collections.Map<kotlin.String, ArgoEventsPubSubEventSource>? = null,

    @Contextual @SerialName(value = "pulsar")
    val pulsar: kotlin.collections.Map<kotlin.String, ArgoEventsPulsarEventSource>? = null,

    @Contextual @SerialName(value = "redis")
    val redis: kotlin.collections.Map<kotlin.String, ArgoEventsRedisEventSource>? = null,

    @Contextual @SerialName(value = "redisStream")
    val redisStream: kotlin.collections.Map<kotlin.String, ArgoEventsRedisStreamEventSource>? = null,

    @SerialName(value = "replicas")
    val replicas: kotlin.Int? = null,

    @Contextual @SerialName(value = "resource")
    val resource: kotlin.collections.Map<kotlin.String, ArgoEventsResourceEventSource>? = null,

    @SerialName(value = "service")
    val service: ArgoEventsService? = null,

    @Contextual @SerialName(value = "sftp")
    val sftp: kotlin.collections.Map<kotlin.String, ArgoEventsSFTPEventSource>? = null,

    @Contextual @SerialName(value = "slack")
    val slack: kotlin.collections.Map<kotlin.String, ArgoEventsSlackEventSource>? = null,

    @Contextual @SerialName(value = "sns")
    val sns: kotlin.collections.Map<kotlin.String, ArgoEventsSNSEventSource>? = null,

    @Contextual @SerialName(value = "sqs")
    val sqs: kotlin.collections.Map<kotlin.String, ArgoEventsSQSEventSource>? = null,

    @Contextual @SerialName(value = "storageGrid")
    val storageGrid: kotlin.collections.Map<kotlin.String, ArgoEventsStorageGridEventSource>? = null,

    @Contextual @SerialName(value = "stripe")
    val stripe: kotlin.collections.Map<kotlin.String, ArgoEventsStripeEventSource>? = null,

    @SerialName(value = "template")
    val template: ArgoEventsTemplate? = null,

    @Contextual @SerialName(value = "webhook")
    val webhook: kotlin.collections.Map<kotlin.String, ArgoEventsWebhookEventSource>? = null

) {


}

