/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ApiMachineryObjectMeta
import io.heapy.argo.client.models.ArgoEventsEventSourceSpec
import io.heapy.argo.client.models.ArgoEventsEventSourceStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param metadata 
 * @param spec 
 * @param status 
 */
@Serializable

data class ArgoEventsEventSource (

    @SerialName(value = "metadata")
    val metadata: ApiMachineryObjectMeta? = null,

    @SerialName(value = "spec")
    val spec: ArgoEventsEventSourceSpec? = null,

    @SerialName(value = "status")
    val status: ArgoEventsEventSourceStatus? = null

) {


}

