/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsEventDependencyFilter
import io.heapy.argo.client.models.ArgoEventsEventDependencyTransformer

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param eventName 
 * @param eventSourceName 
 * @param filters 
 * @param filtersLogicalOperator FiltersLogicalOperator defines how different filters are evaluated together. Available values: and (&&), or (||) Is optional and if left blank treated as and (&&).
 * @param name 
 * @param transform 
 */
@Serializable

data class ArgoEventsEventDependency (

    @SerialName(value = "eventName")
    val eventName: kotlin.String? = null,

    @SerialName(value = "eventSourceName")
    val eventSourceName: kotlin.String? = null,

    @SerialName(value = "filters")
    val filters: ArgoEventsEventDependencyFilter? = null,

    /* FiltersLogicalOperator defines how different filters are evaluated together. Available values: and (&&), or (||) Is optional and if left blank treated as and (&&). */
    @SerialName(value = "filtersLogicalOperator")
    val filtersLogicalOperator: kotlin.String? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "transform")
    val transform: ArgoEventsEventDependencyTransformer? = null

) {


}

