/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArgoEventsTriggerParameter
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * OpenWhiskTrigger refers to the specification of the OpenWhisk trigger.
 *
 * @param actionName Name of the action/function.
 * @param authToken 
 * @param host Host URL of the OpenWhisk.
 * @param namespace Namespace for the action. Defaults to \"_\". +optional.
 * @param parameters 
 * @param payload Payload is the list of key-value extracted from an event payload to construct the request payload.
 * @param version 
 */
@Serializable

data class ArgoEventsOpenWhiskTrigger (

    /* Name of the action/function. */
    @SerialName(value = "actionName")
    val actionName: kotlin.String? = null,

    @SerialName(value = "authToken")
    val authToken: KubernetesSecretKeySelector? = null,

    /* Host URL of the OpenWhisk. */
    @SerialName(value = "host")
    val host: kotlin.String? = null,

    /* Namespace for the action. Defaults to \"_\". +optional. */
    @SerialName(value = "namespace")
    val namespace: kotlin.String? = null,

    @SerialName(value = "parameters")
    val parameters: kotlin.collections.List<ArgoEventsTriggerParameter>? = null,

    /* Payload is the list of key-value extracted from an event payload to construct the request payload. */
    @SerialName(value = "payload")
    val payload: kotlin.collections.List<ArgoEventsTriggerParameter>? = null,

    @SerialName(value = "version")
    val version: kotlin.String? = null

) {


}

