/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * ArtGCStatus maintains state related to ArtifactGC
 *
 * @param notSpecified if this is true, we already checked to see if we need to do it and we don't
 * @param podsRecouped have completed Pods been processed? (mapped by Pod name) used to prevent re-processing the Status of a Pod more than once
 * @param strategiesProcessed have Pods been started to perform this strategy? (enables us not to re-process what we've already done)
 */
@Serializable

data class ArtGCStatus (

    /* if this is true, we already checked to see if we need to do it and we don't */
    @SerialName(value = "notSpecified")
    val notSpecified: kotlin.Boolean? = null,

    /* have completed Pods been processed? (mapped by Pod name) used to prevent re-processing the Status of a Pod more than once */
    @SerialName(value = "podsRecouped")
    val podsRecouped: kotlin.collections.Map<kotlin.String, kotlin.Boolean>? = null,

    /* have Pods been started to perform this strategy? (enables us not to re-process what we've already done) */
    @SerialName(value = "strategiesProcessed")
    val strategiesProcessed: kotlin.collections.Map<kotlin.String, kotlin.Boolean>? = null

) {


}

