/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArchiveStrategy
import io.heapy.argo.client.models.ArtifactGC
import io.heapy.argo.client.models.ArtifactoryArtifact
import io.heapy.argo.client.models.AzureArtifact
import io.heapy.argo.client.models.GCSArtifact
import io.heapy.argo.client.models.GitArtifact
import io.heapy.argo.client.models.HDFSArtifact
import io.heapy.argo.client.models.HTTPArtifact
import io.heapy.argo.client.models.OSSArtifact
import io.heapy.argo.client.models.PluginArtifact
import io.heapy.argo.client.models.RawArtifact
import io.heapy.argo.client.models.S3Artifact

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * ArtifactPaths expands a step from a collection of artifacts
 *
 * @param name name of the artifact. must be unique within a template's inputs/outputs.
 * @param archive 
 * @param archiveLogs ArchiveLogs indicates if the container logs should be archived
 * @param artifactGC 
 * @param artifactory 
 * @param azure 
 * @param deleted Has this been deleted?
 * @param from From allows an artifact to reference an artifact from a previous step
 * @param fromExpression FromExpression, if defined, is evaluated to specify the value for the artifact
 * @param gcs 
 * @param git 
 * @param globalName GlobalName exports an output artifact to the global scope, making it available as '{{outputs.artifacts.XXXX}} and in workflow.status.outputs.artifacts
 * @param hdfs 
 * @param http 
 * @param mode mode bits to use on this file, must be a value between 0 and 0777. Set when loading input artifacts. It is recommended to set the mode value to ensure the artifact has the expected permissions in your container.
 * @param optional Make Artifacts optional, if Artifacts doesn't generate or exist
 * @param oss 
 * @param path Path is the container path to the artifact
 * @param plugin 
 * @param raw 
 * @param recurseMode If mode is set, apply the permission recursively into the artifact if it is a folder
 * @param s3 
 * @param subPath SubPath allows an artifact to be sourced from a subpath within the specified source
 */
@Serializable

data class ArtifactPaths (

    /* name of the artifact. must be unique within a template's inputs/outputs. */
    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "archive")
    val archive: ArchiveStrategy? = null,

    /* ArchiveLogs indicates if the container logs should be archived */
    @SerialName(value = "archiveLogs")
    val archiveLogs: kotlin.Boolean? = null,

    @SerialName(value = "artifactGC")
    val artifactGC: ArtifactGC? = null,

    @SerialName(value = "artifactory")
    val artifactory: ArtifactoryArtifact? = null,

    @SerialName(value = "azure")
    val azure: AzureArtifact? = null,

    /* Has this been deleted? */
    @SerialName(value = "deleted")
    val deleted: kotlin.Boolean? = null,

    /* From allows an artifact to reference an artifact from a previous step */
    @SerialName(value = "from")
    val from: kotlin.String? = null,

    /* FromExpression, if defined, is evaluated to specify the value for the artifact */
    @SerialName(value = "fromExpression")
    val fromExpression: kotlin.String? = null,

    @SerialName(value = "gcs")
    val gcs: GCSArtifact? = null,

    @SerialName(value = "git")
    val git: GitArtifact? = null,

    /* GlobalName exports an output artifact to the global scope, making it available as '{{outputs.artifacts.XXXX}} and in workflow.status.outputs.artifacts */
    @SerialName(value = "globalName")
    val globalName: kotlin.String? = null,

    @SerialName(value = "hdfs")
    val hdfs: HDFSArtifact? = null,

    @SerialName(value = "http")
    val http: HTTPArtifact? = null,

    /* mode bits to use on this file, must be a value between 0 and 0777. Set when loading input artifacts. It is recommended to set the mode value to ensure the artifact has the expected permissions in your container. */
    @SerialName(value = "mode")
    val mode: kotlin.Int? = null,

    /* Make Artifacts optional, if Artifacts doesn't generate or exist */
    @SerialName(value = "optional")
    val optional: kotlin.Boolean? = null,

    @SerialName(value = "oss")
    val oss: OSSArtifact? = null,

    /* Path is the container path to the artifact */
    @SerialName(value = "path")
    val path: kotlin.String? = null,

    @SerialName(value = "plugin")
    val plugin: PluginArtifact? = null,

    @SerialName(value = "raw")
    val raw: RawArtifact? = null,

    /* If mode is set, apply the permission recursively into the artifact if it is a folder */
    @SerialName(value = "recurseMode")
    val recurseMode: kotlin.Boolean? = null,

    @SerialName(value = "s3")
    val s3: S3Artifact? = null,

    /* SubPath allows an artifact to be sourced from a subpath within the specified source */
    @SerialName(value = "subPath")
    val subPath: kotlin.String? = null

) {


}

