/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.Metadata

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * ArtifactGC describes how to delete artifacts from completed Workflows - this is embedded into the WorkflowLevelArtifactGC, and also used for individual Artifacts to override that as needed
 *
 * @param podMetadata 
 * @param serviceAccountName ServiceAccountName is an optional field for specifying the Service Account that should be assigned to the Pod doing the deletion
 * @param strategy Strategy is the strategy to use.
 */
@Serializable

data class ArtifactGC (

    @SerialName(value = "podMetadata")
    val podMetadata: Metadata? = null,

    /* ServiceAccountName is an optional field for specifying the Service Account that should be assigned to the Pod doing the deletion */
    @SerialName(value = "serviceAccountName")
    val serviceAccountName: kotlin.String? = null,

    /* Strategy is the strategy to use. */
    @SerialName(value = "strategy")
    val strategy: kotlin.String? = null

) {


}

