/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * AzureArtifactRepository defines the controller configuration for an Azure Blob Storage artifact repository
 *
 * @param container Container is the container where resources will be stored
 * @param endpoint Endpoint is the service url associated with an account. It is most likely \"https://<ACCOUNT_NAME>.blob.core.windows.net\"
 * @param accountKeySecret 
 * @param blobNameFormat BlobNameFormat is defines the format of how to store blob names. Can reference workflow variables
 * @param useSDKCreds UseSDKCreds tells the driver to figure out credentials based on sdk defaults.
 */
@Serializable

data class AzureArtifactRepository (

    /* Container is the container where resources will be stored */
    @SerialName(value = "container")
    val container: kotlin.String,

    /* Endpoint is the service url associated with an account. It is most likely \"https://<ACCOUNT_NAME>.blob.core.windows.net\" */
    @SerialName(value = "endpoint")
    val endpoint: kotlin.String,

    @SerialName(value = "accountKeySecret")
    val accountKeySecret: KubernetesSecretKeySelector? = null,

    /* BlobNameFormat is defines the format of how to store blob names. Can reference workflow variables */
    @SerialName(value = "blobNameFormat")
    val blobNameFormat: kotlin.String? = null,

    /* UseSDKCreds tells the driver to figure out credentials based on sdk defaults. */
    @SerialName(value = "useSDKCreds")
    val useSDKCreds: kotlin.Boolean? = null

) {


}

