/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * ClientCertAuth holds necessary information for client authentication via certificates
 *
 * @param clientCertSecret 
 * @param clientKeySecret 
 */
@Serializable

data class ClientCertAuth (

    @SerialName(value = "clientCertSecret")
    val clientCertSecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "clientKeySecret")
    val clientKeySecret: KubernetesSecretKeySelector? = null

) {


}

