/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ClusterWorkflowTemplate

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name DEPRECATED: This field is ignored.
 * @param template 
 */
@Serializable

data class ClusterWorkflowTemplateUpdateRequest (

    /* DEPRECATED: This field is ignored. */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "template")
    val template: ClusterWorkflowTemplate? = null

) {


}

