/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ApiMachineryCreateOptions
import io.heapy.argo.client.models.ClusterWorkflowTemplate

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createOptions 
 * @param template 
 */
@Serializable

data class ClusterWorkflowTemplateCreateRequest (

    @SerialName(value = "createOptions")
    val createOptions: ApiMachineryCreateOptions? = null,

    @SerialName(value = "template")
    val template: ClusterWorkflowTemplate? = null

) {


}

