/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param message Message is the condition message
 * @param status Status is the status of the condition
 * @param type Type is the type of condition
 */
@Serializable

data class Condition (

    /* Message is the condition message */
    @SerialName(value = "message")
    val message: kotlin.String? = null,

    /* Status is the status of the condition */
    @SerialName(value = "status")
    val status: kotlin.String? = null,

    /* Type is the type of condition */
    @SerialName(value = "type")
    val type: kotlin.String? = null

) {


}

