/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.Condition
import io.heapy.argo.client.models.KubernetesObjectReference

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlin.time.Instant

/**
 * CronWorkflowStatus is the status of a CronWorkflow
 *
 * @param active Active is a list of active workflows stemming from this CronWorkflow
 * @param conditions Conditions is a list of conditions the CronWorkflow may have
 * @param failed v3.6 and after: Failed counts how many times child workflows failed
 * @param lastScheduledTime Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
 * @param phase v3.6 and after: Phase is an enum of Active or Stopped. It changes to Stopped when stopStrategy.expression is true
 * @param succeeded v3.6 and after: Succeeded counts how many times child workflows succeeded
 */
@Serializable

data class CronWorkflowStatus (

    /* Active is a list of active workflows stemming from this CronWorkflow */
    @SerialName(value = "active")
    val active: kotlin.collections.List<KubernetesObjectReference>? = null,

    /* Conditions is a list of conditions the CronWorkflow may have */
    @SerialName(value = "conditions")
    val conditions: kotlin.collections.List<Condition>? = null,

    /* v3.6 and after: Failed counts how many times child workflows failed */
    @SerialName(value = "failed")
    val failed: kotlin.Int? = null,

    /* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. */
    @Contextual @SerialName(value = "lastScheduledTime")
    val lastScheduledTime: Instant? = null,

    /* v3.6 and after: Phase is an enum of Active or Stopped. It changes to Stopped when stopStrategy.expression is true */
    @SerialName(value = "phase")
    val phase: kotlin.String? = null,

    /* v3.6 and after: Succeeded counts how many times child workflows succeeded */
    @SerialName(value = "succeeded")
    val succeeded: kotlin.Int? = null

) {


}

