/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ApiMachineryObjectMeta
import io.heapy.argo.client.models.StopStrategy
import io.heapy.argo.client.models.WorkflowSpec

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * CronWorkflowSpec is the specification of a CronWorkflow
 *
 * @param workflowSpec 
 * @param concurrencyPolicy ConcurrencyPolicy is the K8s-style concurrency policy that will be used
 * @param failedJobsHistoryLimit FailedJobsHistoryLimit is the number of failed jobs to be kept at a time
 * @param schedules v3.6 and after: Schedules is a list of schedules to run the Workflow in Cron format
 * @param startingDeadlineSeconds StartingDeadlineSeconds is the K8s-style deadline that will limit the time a CronWorkflow will be run after its original scheduled time if it is missed.
 * @param stopStrategy 
 * @param successfulJobsHistoryLimit SuccessfulJobsHistoryLimit is the number of successful jobs to be kept at a time
 * @param `suspend` Suspend is a flag that will stop new CronWorkflows from running if set to true
 * @param timezone Timezone is the timezone against which the cron schedule will be calculated, e.g. \"Asia/Tokyo\". Default is machine's local time.
 * @param `when` v3.6 and after: When is an expression that determines if a run should be scheduled.
 * @param workflowMetadata 
 */
@Serializable

data class CronWorkflowSpec (

    @SerialName(value = "workflowSpec")
    val workflowSpec: WorkflowSpec,

    /* ConcurrencyPolicy is the K8s-style concurrency policy that will be used */
    @SerialName(value = "concurrencyPolicy")
    val concurrencyPolicy: kotlin.String? = null,

    /* FailedJobsHistoryLimit is the number of failed jobs to be kept at a time */
    @SerialName(value = "failedJobsHistoryLimit")
    val failedJobsHistoryLimit: kotlin.Int? = null,

    /* v3.6 and after: Schedules is a list of schedules to run the Workflow in Cron format */
    @SerialName(value = "schedules")
    val schedules: kotlin.collections.List<kotlin.String>? = null,

    /* StartingDeadlineSeconds is the K8s-style deadline that will limit the time a CronWorkflow will be run after its original scheduled time if it is missed. */
    @SerialName(value = "startingDeadlineSeconds")
    val startingDeadlineSeconds: kotlin.Int? = null,

    @SerialName(value = "stopStrategy")
    val stopStrategy: StopStrategy? = null,

    /* SuccessfulJobsHistoryLimit is the number of successful jobs to be kept at a time */
    @SerialName(value = "successfulJobsHistoryLimit")
    val successfulJobsHistoryLimit: kotlin.Int? = null,

    /* Suspend is a flag that will stop new CronWorkflows from running if set to true */
    @SerialName(value = "suspend")
    val `suspend`: kotlin.Boolean? = null,

    /* Timezone is the timezone against which the cron schedule will be calculated, e.g. \"Asia/Tokyo\". Default is machine's local time. */
    @SerialName(value = "timezone")
    val timezone: kotlin.String? = null,

    /* v3.6 and after: When is an expression that determines if a run should be scheduled. */
    @SerialName(value = "when")
    val `when`: kotlin.String? = null,

    @SerialName(value = "workflowMetadata")
    val workflowMetadata: ApiMachineryObjectMeta? = null

) {


}

