/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.DAGTask

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * DAGTemplate is a template subtype for directed acyclic graph templates
 *
 * @param tasks Tasks are a list of DAG tasks
 * @param failFast This flag is for DAG logic. The DAG logic has a built-in \"fail fast\" feature to stop scheduling new steps, as soon as it detects that one of the DAG nodes is failed. Then it waits until all DAG nodes are completed before failing the DAG itself. The FailFast flag default is true,  if set to false, it will allow a DAG to run all branches of the DAG to completion (either success or failure), regardless of the failed outcomes of branches in the DAG. More info and example about this feature at https://github.com/argoproj/argo-workflows/issues/1442
 * @param target Target are one or more names of targets to execute in a DAG
 */
@Serializable

data class DAGTemplate (

    /* Tasks are a list of DAG tasks */
    @SerialName(value = "tasks")
    val tasks: kotlin.collections.List<DAGTask>,

    /* This flag is for DAG logic. The DAG logic has a built-in \"fail fast\" feature to stop scheduling new steps, as soon as it detects that one of the DAG nodes is failed. Then it waits until all DAG nodes are completed before failing the DAG itself. The FailFast flag default is true,  if set to false, it will allow a DAG to run all branches of the DAG to completion (either success or failure), regardless of the failed outcomes of branches in the DAG. More info and example about this feature at https://github.com/argoproj/argo-workflows/issues/1442 */
    @SerialName(value = "failFast")
    val failFast: kotlin.Boolean? = null,

    /* Target are one or more names of targets to execute in a DAG */
    @SerialName(value = "target")
    val target: kotlin.String? = null

) {


}

