/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArtifactPaths

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * DataSource sources external data into a data template
 *
 * @param artifactPaths 
 */
@Serializable

data class DataSource (

    @SerialName(value = "artifactPaths")
    val artifactPaths: ArtifactPaths? = null

) {


}

