/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlin.time.Instant

/**
 * 
 *
 * @param eventName 
 * @param eventSourceName 
 * @param eventSourceType 
 * @param level 
 * @param msg 
 * @param namespace 
 * @param time Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
 */
@Serializable

data class EventsourceLogEntry (

    @SerialName(value = "eventName")
    val eventName: kotlin.String? = null,

    @SerialName(value = "eventSourceName")
    val eventSourceName: kotlin.String? = null,

    @SerialName(value = "eventSourceType")
    val eventSourceType: kotlin.String? = null,

    @SerialName(value = "level")
    val level: kotlin.String? = null,

    @SerialName(value = "msg")
    val msg: kotlin.String? = null,

    @SerialName(value = "namespace")
    val namespace: kotlin.String? = null,

    /* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. */
    @Contextual @SerialName(value = "time")
    val time: Instant? = null

) {


}

