/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * ExecutorConfig holds configurations of an executor container.
 *
 * @param serviceAccountName ServiceAccountName specifies the service account name of the executor container.
 */
@Serializable

data class ExecutorConfig (

    /* ServiceAccountName specifies the service account name of the executor container. */
    @SerialName(value = "serviceAccountName")
    val serviceAccountName: kotlin.String? = null

) {


}

