/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * GCSArtifact is the location of a GCS artifact
 *
 * @param key Key is the path in the bucket where the artifact resides
 * @param bucket Bucket is the name of the bucket
 * @param serviceAccountKeySecret 
 */
@Serializable

data class GCSArtifact (

    /* Key is the path in the bucket where the artifact resides */
    @SerialName(value = "key")
    val key: kotlin.String,

    /* Bucket is the name of the bucket */
    @SerialName(value = "bucket")
    val bucket: kotlin.String? = null,

    @SerialName(value = "serviceAccountKeySecret")
    val serviceAccountKeySecret: KubernetesSecretKeySelector? = null

) {


}

