/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param email 
 * @param emailVerified 
 * @param groups 
 * @param issuer 
 * @param name 
 * @param serviceAccountName 
 * @param serviceAccountNamespace 
 * @param subject 
 */
@Serializable

data class GetUserInfoResponse (

    @SerialName(value = "email")
    val email: kotlin.String? = null,

    @SerialName(value = "emailVerified")
    val emailVerified: kotlin.Boolean? = null,

    @SerialName(value = "groups")
    val groups: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "issuer")
    val issuer: kotlin.String? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "serviceAccountName")
    val serviceAccountName: kotlin.String? = null,

    @SerialName(value = "serviceAccountNamespace")
    val serviceAccountNamespace: kotlin.String? = null,

    @SerialName(value = "subject")
    val subject: kotlin.String? = null

) {


}

