/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * GitArtifact is the location of a git artifact
 *
 * @param repo Repo is the git repository
 * @param branch Branch is the branch to fetch when `SingleBranch` is enabled
 * @param depth Depth specifies clones/fetches should be shallow and include the given number of commits from the branch tip
 * @param disableSubmodules DisableSubmodules disables submodules during git clone
 * @param fetch Fetch specifies a number of refs that should be fetched before checkout
 * @param insecureIgnoreHostKey InsecureIgnoreHostKey disables SSH strict host key checking during git clone
 * @param insecureSkipTLS InsecureSkipTLS disables server certificate verification resulting in insecure HTTPS connections
 * @param passwordSecret 
 * @param revision Revision is the git commit, tag, branch to checkout
 * @param singleBranch SingleBranch enables single branch clone, using the `branch` parameter
 * @param sshPrivateKeySecret 
 * @param usernameSecret 
 */
@Serializable

data class GitArtifact (

    /* Repo is the git repository */
    @SerialName(value = "repo")
    val repo: kotlin.String,

    /* Branch is the branch to fetch when `SingleBranch` is enabled */
    @SerialName(value = "branch")
    val branch: kotlin.String? = null,

    /* Depth specifies clones/fetches should be shallow and include the given number of commits from the branch tip */
    @SerialName(value = "depth")
    val depth: kotlin.Int? = null,

    /* DisableSubmodules disables submodules during git clone */
    @SerialName(value = "disableSubmodules")
    val disableSubmodules: kotlin.Boolean? = null,

    /* Fetch specifies a number of refs that should be fetched before checkout */
    @SerialName(value = "fetch")
    val fetch: kotlin.collections.List<kotlin.String>? = null,

    /* InsecureIgnoreHostKey disables SSH strict host key checking during git clone */
    @SerialName(value = "insecureIgnoreHostKey")
    val insecureIgnoreHostKey: kotlin.Boolean? = null,

    /* InsecureSkipTLS disables server certificate verification resulting in insecure HTTPS connections */
    @SerialName(value = "insecureSkipTLS")
    val insecureSkipTLS: kotlin.Boolean? = null,

    @SerialName(value = "passwordSecret")
    val passwordSecret: KubernetesSecretKeySelector? = null,

    /* Revision is the git commit, tag, branch to checkout */
    @SerialName(value = "revision")
    val revision: kotlin.String? = null,

    /* SingleBranch enables single branch clone, using the `branch` parameter */
    @SerialName(value = "singleBranch")
    val singleBranch: kotlin.Boolean? = null,

    @SerialName(value = "sshPrivateKeySecret")
    val sshPrivateKeySecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "usernameSecret")
    val usernameSecret: KubernetesSecretKeySelector? = null

) {


}

