/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesConfigMapKeySelector
import io.heapy.argo.client.models.KubernetesSecretKeySelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * HDFSArtifactRepository defines the controller configuration for an HDFS artifact repository
 *
 * @param addresses Addresses is accessible addresses of HDFS name nodes
 * @param dataTransferProtection DataTransferProtection is the protection level for HDFS data transfer. It corresponds to the dfs.data.transfer.protection configuration in HDFS.
 * @param force Force copies a file forcibly even if it exists
 * @param hdfsUser HDFSUser is the user to access HDFS file system. It is ignored if either ccache or keytab is used.
 * @param krbCCacheSecret 
 * @param krbConfigConfigMap 
 * @param krbKeytabSecret 
 * @param krbRealm KrbRealm is the Kerberos realm used with Kerberos keytab It must be set if keytab is used.
 * @param krbServicePrincipalName KrbServicePrincipalName is the principal name of Kerberos service It must be set if either ccache or keytab is used.
 * @param krbUsername KrbUsername is the Kerberos username used with Kerberos keytab It must be set if keytab is used.
 * @param pathFormat PathFormat is defines the format of path to store a file. Can reference workflow variables
 */
@Serializable

data class HDFSArtifactRepository (

    /* Addresses is accessible addresses of HDFS name nodes */
    @SerialName(value = "addresses")
    val addresses: kotlin.collections.List<kotlin.String>? = null,

    /* DataTransferProtection is the protection level for HDFS data transfer. It corresponds to the dfs.data.transfer.protection configuration in HDFS. */
    @SerialName(value = "dataTransferProtection")
    val dataTransferProtection: kotlin.String? = null,

    /* Force copies a file forcibly even if it exists */
    @SerialName(value = "force")
    val force: kotlin.Boolean? = null,

    /* HDFSUser is the user to access HDFS file system. It is ignored if either ccache or keytab is used. */
    @SerialName(value = "hdfsUser")
    val hdfsUser: kotlin.String? = null,

    @SerialName(value = "krbCCacheSecret")
    val krbCCacheSecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "krbConfigConfigMap")
    val krbConfigConfigMap: KubernetesConfigMapKeySelector? = null,

    @SerialName(value = "krbKeytabSecret")
    val krbKeytabSecret: KubernetesSecretKeySelector? = null,

    /* KrbRealm is the Kerberos realm used with Kerberos keytab It must be set if keytab is used. */
    @SerialName(value = "krbRealm")
    val krbRealm: kotlin.String? = null,

    /* KrbServicePrincipalName is the principal name of Kerberos service It must be set if either ccache or keytab is used. */
    @SerialName(value = "krbServicePrincipalName")
    val krbServicePrincipalName: kotlin.String? = null,

    /* KrbUsername is the Kerberos username used with Kerberos keytab It must be set if keytab is used. */
    @SerialName(value = "krbUsername")
    val krbUsername: kotlin.String? = null,

    /* PathFormat is defines the format of path to store a file. Can reference workflow variables */
    @SerialName(value = "pathFormat")
    val pathFormat: kotlin.String? = null

) {


}

