/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Header indicate a key-value request header to be used when fetching artifacts over HTTP
 *
 * @param name Name is the header name
 * @param `value` Value is the literal value to use for the header
 */
@Serializable

data class Header (

    /* Name is the header name */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* Value is the literal value to use for the header */
    @SerialName(value = "value")
    val `value`: kotlin.String

) {


}

