/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Histogram is a Histogram prometheus metric
 *
 * @param buckets Buckets is a list of bucket divisors for the histogram
 * @param `value` Value is the value of the metric
 */
@Serializable

data class Histogram (

    /* Buckets is a list of bucket divisors for the histogram */
    @SerialName(value = "buckets")
    val buckets: kotlin.collections.List<@Contextual java.math.BigDecimal>,

    /* Value is the value of the metric */
    @SerialName(value = "value")
    val `value`: kotlin.String

) {


}

