/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.HTTPBodySource
import io.heapy.argo.client.models.HTTPHeader

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param url URL of the HTTP Request
 * @param body Body is content of the HTTP Request
 * @param bodyFrom 
 * @param headers Headers are an optional list of headers to send with HTTP requests
 * @param insecureSkipVerify InsecureSkipVerify is a bool when if set to true will skip TLS verification for the HTTP client
 * @param method Method is HTTP methods for HTTP Request
 * @param successCondition SuccessCondition is an expression if evaluated to true is considered successful
 * @param timeoutSeconds TimeoutSeconds is request timeout for HTTP Request. Default is 30 seconds
 */
@Serializable

data class HTTP (

    /* URL of the HTTP Request */
    @SerialName(value = "url")
    val url: kotlin.String,

    /* Body is content of the HTTP Request */
    @SerialName(value = "body")
    val body: kotlin.String? = null,

    @SerialName(value = "bodyFrom")
    val bodyFrom: HTTPBodySource? = null,

    /* Headers are an optional list of headers to send with HTTP requests */
    @SerialName(value = "headers")
    val headers: kotlin.collections.List<HTTPHeader>? = null,

    /* InsecureSkipVerify is a bool when if set to true will skip TLS verification for the HTTP client */
    @SerialName(value = "insecureSkipVerify")
    val insecureSkipVerify: kotlin.Boolean? = null,

    /* Method is HTTP methods for HTTP Request */
    @SerialName(value = "method")
    val method: kotlin.String? = null,

    /* SuccessCondition is an expression if evaluated to true is considered successful */
    @SerialName(value = "successCondition")
    val successCondition: kotlin.String? = null,

    /* TimeoutSeconds is request timeout for HTTP Request. Default is 30 seconds */
    @SerialName(value = "timeoutSeconds")
    val timeoutSeconds: kotlin.Int? = null

) {


}

