/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * HTTPBodySource contains the source of the HTTP body.
 *
 * @param bytes 
 */
@Serializable

data class HTTPBodySource (

    @SerialName(value = "bytes")
    val bytes: kotlin.ByteArray? = null

) {


}

