/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.Column
import io.heapy.argo.client.models.Link

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param columns 
 * @param links 
 * @param managedNamespace 
 * @param modals 
 * @param navColor 
 */
@Serializable

data class InfoResponse (

    @SerialName(value = "columns")
    val columns: kotlin.collections.List<Column>? = null,

    @SerialName(value = "links")
    val links: kotlin.collections.List<Link>? = null,

    @SerialName(value = "managedNamespace")
    val managedNamespace: kotlin.String? = null,

    @SerialName(value = "modals")
    val modals: kotlin.collections.Map<kotlin.String, kotlin.Boolean>? = null,

    @SerialName(value = "navColor")
    val navColor: kotlin.String? = null

) {


}

