/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.Artifact
import io.heapy.argo.client.models.Parameter

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Inputs are the mechanism for passing parameters, artifacts, volumes from one template to another
 *
 * @param artifacts Artifact are a list of artifacts passed as inputs
 * @param parameters Parameters are a list of parameters passed as inputs
 */
@Serializable

data class Inputs (

    /* Artifact are a list of artifacts passed as inputs */
    @SerialName(value = "artifacts")
    val artifacts: kotlin.collections.List<Artifact>? = null,

    /* Parameters are a list of parameters passed as inputs */
    @SerialName(value = "parameters")
    val parameters: kotlin.collections.List<Parameter>? = null

) {


}

