/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesNodeSelectorRequirement

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm.
 *
 * @param matchExpressions A list of node selector requirements by node's labels.
 * @param matchFields A list of node selector requirements by node's fields.
 */
@Serializable

data class KubernetesNodeSelectorTerm (

    /* A list of node selector requirements by node's labels. */
    @SerialName(value = "matchExpressions")
    val matchExpressions: kotlin.collections.List<KubernetesNodeSelectorRequirement>? = null,

    /* A list of node selector requirements by node's fields. */
    @SerialName(value = "matchFields")
    val matchFields: kotlin.collections.List<KubernetesNodeSelectorRequirement>? = null

) {


}

