/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesExecAction
import io.heapy.argo.client.models.KubernetesHTTPGetAction
import io.heapy.argo.client.models.KubernetesSleepAction
import io.heapy.argo.client.models.KubernetesTCPSocketAction

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * LifecycleHandler defines a specific action that should be taken in a lifecycle hook. One and only one of the fields, except TCPSocket must be specified.
 *
 * @param exec 
 * @param httpGet 
 * @param sleep 
 * @param tcpSocket 
 */
@Serializable

data class KubernetesLifecycleHandler (

    @SerialName(value = "exec")
    val exec: KubernetesExecAction? = null,

    @SerialName(value = "httpGet")
    val httpGet: KubernetesHTTPGetAction? = null,

    @SerialName(value = "sleep")
    val sleep: KubernetesSleepAction? = null,

    @SerialName(value = "tcpSocket")
    val tcpSocket: KubernetesTCPSocketAction? = null

) {


}

