/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesDownwardAPIVolumeFile

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represents downward API info for projecting into a projected volume. Note that this is identical to a downwardAPI volume source without the default mode.
 *
 * @param items Items is a list of DownwardAPIVolume file
 */
@Serializable

data class KubernetesDownwardAPIProjection (

    /* Items is a list of DownwardAPIVolume file */
    @SerialName(value = "items")
    val items: kotlin.collections.List<KubernetesDownwardAPIVolumeFile>? = null

) {


}

