/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * volumeDevice describes a mapping of a raw block device within a container.
 *
 * @param devicePath devicePath is the path inside of the container that the device will be mapped to.
 * @param name name must match the name of a persistentVolumeClaim in the pod
 */
@Serializable

data class KubernetesVolumeDevice (

    /* devicePath is the path inside of the container that the device will be mapped to. */
    @SerialName(value = "devicePath")
    val devicePath: kotlin.String,

    /* name must match the name of a persistentVolumeClaim in the pod */
    @SerialName(value = "name")
    val name: kotlin.String

) {


}

