/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesObjectFieldSelector
import io.heapy.argo.client.models.KubernetesResourceFieldSelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * DownwardAPIVolumeFile represents information to create the file containing the pod field
 *
 * @param path Required: Path is  the relative path name of the file to be created. Must not be absolute or contain the '..' path. Must be utf-8 encoded. The first item of the relative path must not start with '..'
 * @param fieldRef 
 * @param mode Optional: mode bits used to set permissions on this file, must be an octal value between 0000 and 0777 or a decimal value between 0 and 511. YAML accepts both octal and decimal values, JSON requires decimal values for mode bits. If not specified, the volume defaultMode will be used. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.
 * @param resourceFieldRef 
 */
@Serializable

data class KubernetesDownwardAPIVolumeFile (

    /* Required: Path is  the relative path name of the file to be created. Must not be absolute or contain the '..' path. Must be utf-8 encoded. The first item of the relative path must not start with '..' */
    @SerialName(value = "path")
    val path: kotlin.String,

    @SerialName(value = "fieldRef")
    val fieldRef: KubernetesObjectFieldSelector? = null,

    /* Optional: mode bits used to set permissions on this file, must be an octal value between 0000 and 0777 or a decimal value between 0 and 511. YAML accepts both octal and decimal values, JSON requires decimal values for mode bits. If not specified, the volume defaultMode will be used. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set. */
    @SerialName(value = "mode")
    val mode: kotlin.Int? = null,

    @SerialName(value = "resourceFieldRef")
    val resourceFieldRef: KubernetesResourceFieldSelector? = null

) {


}

