/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ApiMachineryLabelSelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * ClusterTrustBundleProjection describes how to select a set of ClusterTrustBundle objects and project their contents into the pod filesystem.
 *
 * @param path Relative path from the volume root to write the bundle.
 * @param labelSelector 
 * @param name Select a single ClusterTrustBundle by object name.  Mutually-exclusive with signerName and labelSelector.
 * @param optional If true, don't block pod startup if the referenced ClusterTrustBundle(s) aren't available.  If using name, then the named ClusterTrustBundle is allowed not to exist.  If using signerName, then the combination of signerName and labelSelector is allowed to match zero ClusterTrustBundles.
 * @param signerName Select all ClusterTrustBundles that match this signer name. Mutually-exclusive with name.  The contents of all selected ClusterTrustBundles will be unified and deduplicated.
 */
@Serializable

data class KubernetesClusterTrustBundleProjection (

    /* Relative path from the volume root to write the bundle. */
    @SerialName(value = "path")
    val path: kotlin.String,

    @SerialName(value = "labelSelector")
    val labelSelector: ApiMachineryLabelSelector? = null,

    /* Select a single ClusterTrustBundle by object name.  Mutually-exclusive with signerName and labelSelector. */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* If true, don't block pod startup if the referenced ClusterTrustBundle(s) aren't available.  If using name, then the named ClusterTrustBundle is allowed not to exist.  If using signerName, then the combination of signerName and labelSelector is allowed to match zero ClusterTrustBundles. */
    @SerialName(value = "optional")
    val optional: kotlin.Boolean? = null,

    /* Select all ClusterTrustBundles that match this signer name. Mutually-exclusive with name.  The contents of all selected ClusterTrustBundles will be unified and deduplicated. */
    @SerialName(value = "signerName")
    val signerName: kotlin.String? = null

) {


}

