/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represents a vSphere volume resource.
 *
 * @param volumePath volumePath is the path that identifies vSphere volume vmdk
 * @param fsType fsType is filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified.
 * @param storagePolicyID storagePolicyID is the storage Policy Based Management (SPBM) profile ID associated with the StoragePolicyName.
 * @param storagePolicyName storagePolicyName is the storage Policy Based Management (SPBM) profile name.
 */
@Serializable

data class KubernetesVsphereVirtualDiskVolumeSource (

    /* volumePath is the path that identifies vSphere volume vmdk */
    @SerialName(value = "volumePath")
    val volumePath: kotlin.String,

    /* fsType is filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. */
    @SerialName(value = "fsType")
    val fsType: kotlin.String? = null,

    /* storagePolicyID is the storage Policy Based Management (SPBM) profile ID associated with the StoragePolicyName. */
    @SerialName(value = "storagePolicyID")
    val storagePolicyID: kotlin.String? = null,

    /* storagePolicyName is the storage Policy Based Management (SPBM) profile name. */
    @SerialName(value = "storagePolicyName")
    val storagePolicyName: kotlin.String? = null

) {


}

