/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * ContainerPort represents a network port in a single container.
 *
 * @param containerPort Number of port to expose on the pod's IP address. This must be a valid port number, 0 < x < 65536.
 * @param hostIP What host IP to bind the external port to.
 * @param hostPort Number of port to expose on the host. If specified, this must be a valid port number, 0 < x < 65536. If HostNetwork is specified, this must match ContainerPort. Most containers do not need this.
 * @param name If specified, this must be an IANA_SVC_NAME and unique within the pod. Each named port in a pod must have a unique name. Name for the port that can be referred to by services.
 * @param protocol Protocol for port. Must be UDP, TCP, or SCTP. Defaults to \"TCP\".
 */
@Serializable

data class KubernetesContainerPort (

    /* Number of port to expose on the pod's IP address. This must be a valid port number, 0 < x < 65536. */
    @SerialName(value = "containerPort")
    val containerPort: kotlin.Int,

    /* What host IP to bind the external port to. */
    @SerialName(value = "hostIP")
    val hostIP: kotlin.String? = null,

    /* Number of port to expose on the host. If specified, this must be a valid port number, 0 < x < 65536. If HostNetwork is specified, this must match ContainerPort. Most containers do not need this. */
    @SerialName(value = "hostPort")
    val hostPort: kotlin.Int? = null,

    /* If specified, this must be an IANA_SVC_NAME and unique within the pod. Each named port in a pod must have a unique name. Name for the port that can be referred to by services. */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* Protocol for port. Must be UDP, TCP, or SCTP. Defaults to \"TCP\". */
    @SerialName(value = "protocol")
    val protocol: kotlin.String? = null

) {


}

