/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesNodeSelectorTerm

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * An empty preferred scheduling term matches all objects with implicit weight 0 (i.e. it's a no-op). A null preferred scheduling term matches no objects (i.e. is also a no-op).
 *
 * @param preference 
 * @param weight Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
 */
@Serializable

data class KubernetesPreferredSchedulingTerm (

    @SerialName(value = "preference")
    val preference: KubernetesNodeSelectorTerm,

    /* Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100. */
    @SerialName(value = "weight")
    val weight: kotlin.Int

) {


}

