/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesHTTPHeader

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * HTTPGetAction describes an action based on HTTP Get requests.
 *
 * @param port 
 * @param host Host name to connect to, defaults to the pod IP. You probably want to set \"Host\" in httpHeaders instead.
 * @param httpHeaders Custom headers to set in the request. HTTP allows repeated headers.
 * @param path Path to access on the HTTP server.
 * @param scheme Scheme to use for connecting to the host. Defaults to HTTP.
 */
@Serializable

data class KubernetesHTTPGetAction (

    @SerialName(value = "port")
    val port: kotlin.String,

    /* Host name to connect to, defaults to the pod IP. You probably want to set \"Host\" in httpHeaders instead. */
    @SerialName(value = "host")
    val host: kotlin.String? = null,

    /* Custom headers to set in the request. HTTP allows repeated headers. */
    @SerialName(value = "httpHeaders")
    val httpHeaders: kotlin.collections.List<KubernetesHTTPHeader>? = null,

    /* Path to access on the HTTP server. */
    @SerialName(value = "path")
    val path: kotlin.String? = null,

    /* Scheme to use for connecting to the host. Defaults to HTTP. */
    @SerialName(value = "scheme")
    val scheme: kotlin.String? = null

) {


}

