/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represents an NFS mount that lasts the lifetime of a pod. NFS volumes do not support ownership management or SELinux relabeling.
 *
 * @param path path that is exported by the NFS server. More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs
 * @param server server is the hostname or IP address of the NFS server. More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs
 * @param readOnly readOnly here will force the NFS export to be mounted with read-only permissions. Defaults to false. More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs
 */
@Serializable

data class KubernetesNFSVolumeSource (

    /* path that is exported by the NFS server. More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs */
    @SerialName(value = "path")
    val path: kotlin.String,

    /* server is the hostname or IP address of the NFS server. More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs */
    @SerialName(value = "server")
    val server: kotlin.String,

    /* readOnly here will force the NFS export to be mounted with read-only permissions. Defaults to false. More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs */
    @SerialName(value = "readOnly")
    val readOnly: kotlin.Boolean? = null

) {


}

