/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * HTTPHeader describes a custom header to be used in HTTP probes
 *
 * @param name The header field name. This will be canonicalized upon output, so case-variant names will be understood as the same header.
 * @param `value` The header field value
 */
@Serializable

data class KubernetesHTTPHeader (

    /* The header field name. This will be canonicalized upon output, so case-variant names will be understood as the same header. */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* The header field value */
    @SerialName(value = "value")
    val `value`: kotlin.String

) {


}

