/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * ObjectFieldSelector selects an APIVersioned field of an object.
 *
 * @param fieldPath Path of the field to select in the specified API version.
 * @param apiVersion Version of the schema the FieldPath is written in terms of, defaults to \"v1\".
 */
@Serializable

data class KubernetesObjectFieldSelector (

    /* Path of the field to select in the specified API version. */
    @SerialName(value = "fieldPath")
    val fieldPath: kotlin.String,

    /* Version of the schema the FieldPath is written in terms of, defaults to \"v1\". */
    @SerialName(value = "apiVersion")
    val apiVersion: kotlin.String? = null

) {


}

