/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesLocalObjectReference

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * ScaleIOVolumeSource represents a persistent ScaleIO volume
 *
 * @param gateway gateway is the host address of the ScaleIO API Gateway.
 * @param secretRef 
 * @param system system is the name of the storage system as configured in ScaleIO.
 * @param fsType fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Default is \"xfs\".
 * @param protectionDomain protectionDomain is the name of the ScaleIO Protection Domain for the configured storage.
 * @param readOnly readOnly Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
 * @param sslEnabled sslEnabled Flag enable/disable SSL communication with Gateway, default false
 * @param storageMode storageMode indicates whether the storage for a volume should be ThickProvisioned or ThinProvisioned. Default is ThinProvisioned.
 * @param storagePool storagePool is the ScaleIO Storage Pool associated with the protection domain.
 * @param volumeName volumeName is the name of a volume already created in the ScaleIO system that is associated with this volume source.
 */
@Serializable

data class KubernetesScaleIOVolumeSource (

    /* gateway is the host address of the ScaleIO API Gateway. */
    @SerialName(value = "gateway")
    val gateway: kotlin.String,

    @SerialName(value = "secretRef")
    val secretRef: KubernetesLocalObjectReference,

    /* system is the name of the storage system as configured in ScaleIO. */
    @SerialName(value = "system")
    val system: kotlin.String,

    /* fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Default is \"xfs\". */
    @SerialName(value = "fsType")
    val fsType: kotlin.String? = null,

    /* protectionDomain is the name of the ScaleIO Protection Domain for the configured storage. */
    @SerialName(value = "protectionDomain")
    val protectionDomain: kotlin.String? = null,

    /* readOnly Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. */
    @SerialName(value = "readOnly")
    val readOnly: kotlin.Boolean? = null,

    /* sslEnabled Flag enable/disable SSL communication with Gateway, default false */
    @SerialName(value = "sslEnabled")
    val sslEnabled: kotlin.Boolean? = null,

    /* storageMode indicates whether the storage for a volume should be ThickProvisioned or ThinProvisioned. Default is ThinProvisioned. */
    @SerialName(value = "storageMode")
    val storageMode: kotlin.String? = null,

    /* storagePool is the ScaleIO Storage Pool associated with the protection domain. */
    @SerialName(value = "storagePool")
    val storagePool: kotlin.String? = null,

    /* volumeName is the name of a volume already created in the ScaleIO system that is associated with this volume source. */
    @SerialName(value = "volumeName")
    val volumeName: kotlin.String? = null

) {


}

