/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesNodeSelectorTerm

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A node selector represents the union of the results of one or more label queries over a set of nodes; that is, it represents the OR of the selectors represented by the node selector terms.
 *
 * @param nodeSelectorTerms Required. A list of node selector terms. The terms are ORed.
 */
@Serializable

data class KubernetesNodeSelector (

    /* Required. A list of node selector terms. The terms are ORed. */
    @SerialName(value = "nodeSelectorTerms")
    val nodeSelectorTerms: kotlin.collections.List<KubernetesNodeSelectorTerm>

) {


}

