/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * TypedLocalObjectReference contains enough information to let you locate the typed referenced object inside the same namespace.
 *
 * @param kind Kind is the type of resource being referenced
 * @param name Name is the name of resource being referenced
 * @param apiGroup APIGroup is the group for the resource being referenced. If APIGroup is not specified, the specified Kind must be in the core API group. For any other third-party types, APIGroup is required.
 */
@Serializable

data class KubernetesTypedLocalObjectReference (

    /* Kind is the type of resource being referenced */
    @SerialName(value = "kind")
    val kind: kotlin.String,

    /* Name is the name of resource being referenced */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* APIGroup is the group for the resource being referenced. If APIGroup is not specified, the specified Kind must be in the core API group. For any other third-party types, APIGroup is required. */
    @SerialName(value = "apiGroup")
    val apiGroup: kotlin.String? = null

) {


}

