/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represents a Quobyte mount that lasts the lifetime of a pod. Quobyte volumes do not support ownership management or SELinux relabeling.
 *
 * @param registry registry represents a single or multiple Quobyte Registry services specified as a string as host:port pair (multiple entries are separated with commas) which acts as the central registry for volumes
 * @param volume volume is a string that references an already created Quobyte volume by name.
 * @param group group to map volume access to Default is no group
 * @param readOnly readOnly here will force the Quobyte volume to be mounted with read-only permissions. Defaults to false.
 * @param tenant tenant owning the given Quobyte volume in the Backend Used with dynamically provisioned Quobyte volumes, value is set by the plugin
 * @param user user to map volume access to Defaults to serivceaccount user
 */
@Serializable

data class KubernetesQuobyteVolumeSource (

    /* registry represents a single or multiple Quobyte Registry services specified as a string as host:port pair (multiple entries are separated with commas) which acts as the central registry for volumes */
    @SerialName(value = "registry")
    val registry: kotlin.String,

    /* volume is a string that references an already created Quobyte volume by name. */
    @SerialName(value = "volume")
    val volume: kotlin.String,

    /* group to map volume access to Default is no group */
    @SerialName(value = "group")
    val group: kotlin.String? = null,

    /* readOnly here will force the Quobyte volume to be mounted with read-only permissions. Defaults to false. */
    @SerialName(value = "readOnly")
    val readOnly: kotlin.Boolean? = null,

    /* tenant owning the given Quobyte volume in the Backend Used with dynamically provisioned Quobyte volumes, value is set by the plugin */
    @SerialName(value = "tenant")
    val tenant: kotlin.String? = null,

    /* user to map volume access to Defaults to serivceaccount user */
    @SerialName(value = "user")
    val user: kotlin.String? = null

) {


}

