/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesLocalObjectReference

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represents a StorageOS persistent volume resource.
 *
 * @param fsType fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified.
 * @param readOnly readOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
 * @param secretRef 
 * @param volumeName volumeName is the human-readable name of the StorageOS volume.  Volume names are only unique within a namespace.
 * @param volumeNamespace volumeNamespace specifies the scope of the volume within StorageOS.  If no namespace is specified then the Pod's namespace will be used.  This allows the Kubernetes name scoping to be mirrored within StorageOS for tighter integration. Set VolumeName to any name to override the default behaviour. Set to \"default\" if you are not using namespaces within StorageOS. Namespaces that do not pre-exist within StorageOS will be created.
 */
@Serializable

data class KubernetesStorageOSVolumeSource (

    /* fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. */
    @SerialName(value = "fsType")
    val fsType: kotlin.String? = null,

    /* readOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. */
    @SerialName(value = "readOnly")
    val readOnly: kotlin.Boolean? = null,

    @SerialName(value = "secretRef")
    val secretRef: KubernetesLocalObjectReference? = null,

    /* volumeName is the human-readable name of the StorageOS volume.  Volume names are only unique within a namespace. */
    @SerialName(value = "volumeName")
    val volumeName: kotlin.String? = null,

    /* volumeNamespace specifies the scope of the volume within StorageOS.  If no namespace is specified then the Pod's namespace will be used.  This allows the Kubernetes name scoping to be mirrored within StorageOS for tighter integration. Set VolumeName to any name to override the default behaviour. Set to \"default\" if you are not using namespaces within StorageOS. Namespaces that do not pre-exist within StorageOS will be created. */
    @SerialName(value = "volumeNamespace")
    val volumeNamespace: kotlin.String? = null

) {


}

