/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * GRPCAction specifies an action involving a GRPC service.
 *
 * @param port Port number of the gRPC service. Number must be in the range 1 to 65535.
 * @param service Service is the name of the service to place in the gRPC HealthCheckRequest (see https://github.com/grpc/grpc/blob/master/doc/health-checking.md).  If this is not specified, the default behavior is defined by gRPC.
 */
@Serializable

data class KubernetesGRPCAction (

    /* Port number of the gRPC service. Number must be in the range 1 to 65535. */
    @SerialName(value = "port")
    val port: kotlin.Int,

    /* Service is the name of the service to place in the gRPC HealthCheckRequest (see https://github.com/grpc/grpc/blob/master/doc/health-checking.md).  If this is not specified, the default behavior is defined by gRPC. */
    @SerialName(value = "service")
    val service: kotlin.String? = null

) {


}

