/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * PortworxVolumeSource represents a Portworx volume resource.
 *
 * @param volumeID volumeID uniquely identifies a Portworx volume
 * @param fsType fSType represents the filesystem type to mount Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\". Implicitly inferred to be \"ext4\" if unspecified.
 * @param readOnly readOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
 */
@Serializable

data class KubernetesPortworxVolumeSource (

    /* volumeID uniquely identifies a Portworx volume */
    @SerialName(value = "volumeID")
    val volumeID: kotlin.String,

    /* fSType represents the filesystem type to mount Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\". Implicitly inferred to be \"ext4\" if unspecified. */
    @SerialName(value = "fsType")
    val fsType: kotlin.String? = null,

    /* readOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. */
    @SerialName(value = "readOnly")
    val readOnly: kotlin.Boolean? = null

) {


}

