/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * PodDNSConfigOption defines DNS resolver options of a pod.
 *
 * @param name Name is this DNS resolver option's name. Required.
 * @param `value` Value is this DNS resolver option's value.
 */
@Serializable

data class KubernetesPodDNSConfigOption (

    /* Name is this DNS resolver option's name. Required. */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* Value is this DNS resolver option's value. */
    @SerialName(value = "value")
    val `value`: kotlin.String? = null

) {


}

