/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * AzureDisk represents an Azure Data Disk mount on the host and bind mount to the pod.
 *
 * @param diskName diskName is the Name of the data disk in the blob storage
 * @param diskURI diskURI is the URI of data disk in the blob storage
 * @param cachingMode cachingMode is the Host Caching mode: None, Read Only, Read Write.
 * @param fsType fsType is Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified.
 * @param kind kind expected values are Shared: multiple blob disks per storage account  Dedicated: single blob disk per storage account  Managed: azure managed data disk (only in managed availability set). defaults to shared
 * @param readOnly readOnly Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
 */
@Serializable

data class KubernetesAzureDiskVolumeSource (

    /* diskName is the Name of the data disk in the blob storage */
    @SerialName(value = "diskName")
    val diskName: kotlin.String,

    /* diskURI is the URI of data disk in the blob storage */
    @SerialName(value = "diskURI")
    val diskURI: kotlin.String,

    /* cachingMode is the Host Caching mode: None, Read Only, Read Write. */
    @SerialName(value = "cachingMode")
    val cachingMode: kotlin.String? = null,

    /* fsType is Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. */
    @SerialName(value = "fsType")
    val fsType: kotlin.String? = null,

    /* kind expected values are Shared: multiple blob disks per storage account  Dedicated: single blob disk per storage account  Managed: azure managed data disk (only in managed availability set). defaults to shared */
    @SerialName(value = "kind")
    val kind: kotlin.String? = null,

    /* readOnly Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. */
    @SerialName(value = "readOnly")
    val readOnly: kotlin.Boolean? = null

) {


}

