/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Selects a key from a ConfigMap.
 *
 * @param key The key to select.
 * @param name Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
 * @param optional Specify whether the ConfigMap or its key must be defined
 */
@Serializable

data class KubernetesConfigMapKeySelector (

    /* The key to select. */
    @SerialName(value = "key")
    val key: kotlin.String,

    /* Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* Specify whether the ConfigMap or its key must be defined */
    @SerialName(value = "optional")
    val optional: kotlin.Boolean? = null

) {


}

