/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * AzureFile represents an Azure File Service mount on the host and bind mount to the pod.
 *
 * @param secretName secretName is the  name of secret that contains Azure Storage Account Name and Key
 * @param shareName shareName is the azure share Name
 * @param readOnly readOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
 */
@Serializable

data class KubernetesAzureFileVolumeSource (

    /* secretName is the  name of secret that contains Azure Storage Account Name and Key */
    @SerialName(value = "secretName")
    val secretName: kotlin.String,

    /* shareName is the azure share Name */
    @SerialName(value = "shareName")
    val shareName: kotlin.String,

    /* readOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. */
    @SerialName(value = "readOnly")
    val readOnly: kotlin.Boolean? = null

) {


}

