/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesAppArmorProfile
import io.heapy.argo.client.models.KubernetesCapabilities
import io.heapy.argo.client.models.KubernetesSELinuxOptions
import io.heapy.argo.client.models.KubernetesSeccompProfile
import io.heapy.argo.client.models.KubernetesWindowsSecurityContextOptions

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * SecurityContext holds security configuration that will be applied to a container. Some fields are present in both SecurityContext and PodSecurityContext.  When both are set, the values in SecurityContext take precedence.
 *
 * @param allowPrivilegeEscalation AllowPrivilegeEscalation controls whether a process can gain more privileges than its parent process. This bool directly controls if the no_new_privs flag will be set on the container process. AllowPrivilegeEscalation is true always when the container is: 1) run as Privileged 2) has CAP_SYS_ADMIN Note that this field cannot be set when spec.os.name is windows.
 * @param appArmorProfile 
 * @param capabilities 
 * @param privileged Run container in privileged mode. Processes in privileged containers are essentially equivalent to root on the host. Defaults to false. Note that this field cannot be set when spec.os.name is windows.
 * @param procMount procMount denotes the type of proc mount to use for the containers. The default value is Default which uses the container runtime defaults for readonly paths and masked paths. This requires the ProcMountType feature flag to be enabled. Note that this field cannot be set when spec.os.name is windows.
 * @param readOnlyRootFilesystem Whether this container has a read-only root filesystem. Default is false. Note that this field cannot be set when spec.os.name is windows.
 * @param runAsGroup The GID to run the entrypoint of the container process. Uses runtime default if unset. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows.
 * @param runAsNonRoot Indicates that the container must run as a non-root user. If true, the Kubelet will validate the image at runtime to ensure that it does not run as UID 0 (root) and fail to start the container if it does. If unset or false, no such validation will be performed. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
 * @param runAsUser The UID to run the entrypoint of the container process. Defaults to user specified in image metadata if unspecified. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows.
 * @param seLinuxOptions 
 * @param seccompProfile 
 * @param windowsOptions 
 */
@Serializable

data class KubernetesSecurityContext (

    /* AllowPrivilegeEscalation controls whether a process can gain more privileges than its parent process. This bool directly controls if the no_new_privs flag will be set on the container process. AllowPrivilegeEscalation is true always when the container is: 1) run as Privileged 2) has CAP_SYS_ADMIN Note that this field cannot be set when spec.os.name is windows. */
    @SerialName(value = "allowPrivilegeEscalation")
    val allowPrivilegeEscalation: kotlin.Boolean? = null,

    @SerialName(value = "appArmorProfile")
    val appArmorProfile: KubernetesAppArmorProfile? = null,

    @SerialName(value = "capabilities")
    val capabilities: KubernetesCapabilities? = null,

    /* Run container in privileged mode. Processes in privileged containers are essentially equivalent to root on the host. Defaults to false. Note that this field cannot be set when spec.os.name is windows. */
    @SerialName(value = "privileged")
    val privileged: kotlin.Boolean? = null,

    /* procMount denotes the type of proc mount to use for the containers. The default value is Default which uses the container runtime defaults for readonly paths and masked paths. This requires the ProcMountType feature flag to be enabled. Note that this field cannot be set when spec.os.name is windows. */
    @SerialName(value = "procMount")
    val procMount: kotlin.String? = null,

    /* Whether this container has a read-only root filesystem. Default is false. Note that this field cannot be set when spec.os.name is windows. */
    @SerialName(value = "readOnlyRootFilesystem")
    val readOnlyRootFilesystem: kotlin.Boolean? = null,

    /* The GID to run the entrypoint of the container process. Uses runtime default if unset. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows. */
    @SerialName(value = "runAsGroup")
    val runAsGroup: kotlin.Int? = null,

    /* Indicates that the container must run as a non-root user. If true, the Kubelet will validate the image at runtime to ensure that it does not run as UID 0 (root) and fail to start the container if it does. If unset or false, no such validation will be performed. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. */
    @SerialName(value = "runAsNonRoot")
    val runAsNonRoot: kotlin.Boolean? = null,

    /* The UID to run the entrypoint of the container process. Defaults to user specified in image metadata if unspecified. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows. */
    @SerialName(value = "runAsUser")
    val runAsUser: kotlin.Int? = null,

    @SerialName(value = "seLinuxOptions")
    val seLinuxOptions: KubernetesSELinuxOptions? = null,

    @SerialName(value = "seccompProfile")
    val seccompProfile: KubernetesSeccompProfile? = null,

    @SerialName(value = "windowsOptions")
    val windowsOptions: KubernetesWindowsSecurityContextOptions? = null

) {


}

