/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ApiMachineryObjectMeta
import io.heapy.argo.client.models.KubernetesPersistentVolumeClaimSpec

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * PersistentVolumeClaimTemplate is used to produce PersistentVolumeClaim objects as part of an EphemeralVolumeSource.
 *
 * @param spec 
 * @param metadata 
 */
@Serializable

data class KubernetesPersistentVolumeClaimTemplate (

    @SerialName(value = "spec")
    val spec: KubernetesPersistentVolumeClaimSpec,

    @SerialName(value = "metadata")
    val metadata: ApiMachineryObjectMeta? = null

) {


}

