/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * WindowsSecurityContextOptions contain Windows-specific options and credentials.
 *
 * @param gmsaCredentialSpec GMSACredentialSpec is where the GMSA admission webhook (https://github.com/kubernetes-sigs/windows-gmsa) inlines the contents of the GMSA credential spec named by the GMSACredentialSpecName field.
 * @param gmsaCredentialSpecName GMSACredentialSpecName is the name of the GMSA credential spec to use.
 * @param hostProcess HostProcess determines if a container should be run as a 'Host Process' container. All of a Pod's containers must have the same effective HostProcess value (it is not allowed to have a mix of HostProcess containers and non-HostProcess containers). In addition, if HostProcess is true then HostNetwork must also be set to true.
 * @param runAsUserName The UserName in Windows to run the entrypoint of the container process. Defaults to the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
 */
@Serializable

data class KubernetesWindowsSecurityContextOptions (

    /* GMSACredentialSpec is where the GMSA admission webhook (https://github.com/kubernetes-sigs/windows-gmsa) inlines the contents of the GMSA credential spec named by the GMSACredentialSpecName field. */
    @SerialName(value = "gmsaCredentialSpec")
    val gmsaCredentialSpec: kotlin.String? = null,

    /* GMSACredentialSpecName is the name of the GMSA credential spec to use. */
    @SerialName(value = "gmsaCredentialSpecName")
    val gmsaCredentialSpecName: kotlin.String? = null,

    /* HostProcess determines if a container should be run as a 'Host Process' container. All of a Pod's containers must have the same effective HostProcess value (it is not allowed to have a mix of HostProcess containers and non-HostProcess containers). In addition, if HostProcess is true then HostNetwork must also be set to true. */
    @SerialName(value = "hostProcess")
    val hostProcess: kotlin.Boolean? = null,

    /* The UserName in Windows to run the entrypoint of the container process. Defaults to the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. */
    @SerialName(value = "runAsUserName")
    val runAsUserName: kotlin.String? = null

) {


}

