/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represents a Fibre Channel volume. Fibre Channel volumes can only be mounted as read/write once. Fibre Channel volumes support ownership management and SELinux relabeling.
 *
 * @param fsType fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified.
 * @param lun lun is Optional: FC target lun number
 * @param readOnly readOnly is Optional: Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
 * @param targetWWNs targetWWNs is Optional: FC target worldwide names (WWNs)
 * @param wwids wwids Optional: FC volume world wide identifiers (wwids) Either wwids or combination of targetWWNs and lun must be set, but not both simultaneously.
 */
@Serializable

data class KubernetesFCVolumeSource (

    /* fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. */
    @SerialName(value = "fsType")
    val fsType: kotlin.String? = null,

    /* lun is Optional: FC target lun number */
    @SerialName(value = "lun")
    val lun: kotlin.Int? = null,

    /* readOnly is Optional: Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. */
    @SerialName(value = "readOnly")
    val readOnly: kotlin.Boolean? = null,

    /* targetWWNs is Optional: FC target worldwide names (WWNs) */
    @SerialName(value = "targetWWNs")
    val targetWWNs: kotlin.collections.List<kotlin.String>? = null,

    /* wwids Optional: FC volume world wide identifiers (wwids) Either wwids or combination of targetWWNs and lun must be set, but not both simultaneously. */
    @SerialName(value = "wwids")
    val wwids: kotlin.collections.List<kotlin.String>? = null

) {


}

