/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * SleepAction describes a \"sleep\" action.
 *
 * @param seconds Seconds is the number of seconds to sleep.
 */
@Serializable

data class KubernetesSleepAction (

    /* Seconds is the number of seconds to sleep. */
    @SerialName(value = "seconds")
    val seconds: kotlin.Int

) {


}

