/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * SELinuxOptions are the labels to be applied to the container
 *
 * @param level Level is SELinux level label that applies to the container.
 * @param role Role is a SELinux role label that applies to the container.
 * @param type Type is a SELinux type label that applies to the container.
 * @param user User is a SELinux user label that applies to the container.
 */
@Serializable

data class KubernetesSELinuxOptions (

    /* Level is SELinux level label that applies to the container. */
    @SerialName(value = "level")
    val level: kotlin.String? = null,

    /* Role is a SELinux role label that applies to the container. */
    @SerialName(value = "role")
    val role: kotlin.String? = null,

    /* Type is a SELinux type label that applies to the container. */
    @SerialName(value = "type")
    val type: kotlin.String? = null,

    /* User is a SELinux user label that applies to the container. */
    @SerialName(value = "user")
    val user: kotlin.String? = null

) {


}

