/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.Arguments
import io.heapy.argo.client.models.TemplateRef

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param arguments 
 * @param expression Expression is a condition expression for when a node will be retried. If it evaluates to false, the node will not be retried and the retry strategy will be ignored
 * @param template Template is the name of the template to execute by the hook
 * @param templateRef 
 */
@Serializable

data class LifecycleHook (

    @SerialName(value = "arguments")
    val arguments: Arguments? = null,

    /* Expression is a condition expression for when a node will be retried. If it evaluates to false, the node will not be retried and the retry strategy will be ignored */
    @SerialName(value = "expression")
    val expression: kotlin.String? = null,

    /* Template is the name of the template to execute by the hook */
    @SerialName(value = "template")
    val template: kotlin.String? = null,

    @SerialName(value = "templateRef")
    val templateRef: TemplateRef? = null

) {


}

