/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A link to another app.
 *
 * @param name The name of the link, E.g. \"Workflow Logs\" or \"Pod Logs\"
 * @param scope \"workflow\", \"pod\", \"pod-logs\", \"event-source-logs\", \"sensor-logs\", \"workflow-list\" or \"chat\"
 * @param target Target attribute specifies where a linked document will be opened when a user clicks on a link. E.g. \"_blank\", \"_self\". If the target is _blank, it will open in a new tab.
 * @param url The URL. Can contain \"${metadata.namespace}\", \"${metadata.name}\", \"${status.startedAt}\", \"${status.finishedAt}\" or any other element in workflow yaml, e.g. \"${metadata.annotations.userDefinedKey}\"
 */
@Serializable

data class Link (

    /* The name of the link, E.g. \"Workflow Logs\" or \"Pod Logs\" */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* \"workflow\", \"pod\", \"pod-logs\", \"event-source-logs\", \"sensor-logs\", \"workflow-list\" or \"chat\" */
    @SerialName(value = "scope")
    val scope: kotlin.String,

    /* Target attribute specifies where a linked document will be opened when a user clicks on a link. E.g. \"_blank\", \"_self\". If the target is _blank, it will open in a new tab. */
    @SerialName(value = "target")
    val target: kotlin.String,

    /* The URL. Can contain \"${metadata.namespace}\", \"${metadata.name}\", \"${status.startedAt}\", \"${status.finishedAt}\" or any other element in workflow yaml, e.g. \"${metadata.annotations.userDefinedKey}\" */
    @SerialName(value = "url")
    val url: kotlin.String

) {


}

