/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param content 
 * @param podName 
 */
@Serializable

data class LogEntry (

    @SerialName(value = "content")
    val content: kotlin.String? = null,

    @SerialName(value = "podName")
    val podName: kotlin.String? = null

) {


}

