/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.Cache

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Memoization enables caching for the Outputs of the template
 *
 * @param cache 
 * @param key Key is the key to use as the caching key
 * @param maxAge MaxAge is the maximum age (e.g. \"180s\", \"24h\") of an entry that is still considered valid. If an entry is older than the MaxAge, it will be ignored.
 */
@Serializable

data class Memoize (

    @SerialName(value = "cache")
    val cache: Cache,

    /* Key is the key to use as the caching key */
    @SerialName(value = "key")
    val key: kotlin.String,

    /* MaxAge is the maximum age (e.g. \"180s\", \"24h\") of an entry that is still considered valid. If an entry is older than the MaxAge, it will be ignored. */
    @SerialName(value = "maxAge")
    val maxAge: kotlin.String

) {


}

