/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Mutex holds Mutex configuration
 *
 * @param database Database specifies this is database controlled if this is set true
 * @param name name of the mutex
 * @param namespace Namespace is the namespace of the mutex, default: [namespace of workflow]
 */
@Serializable

data class Mutex (

    /* Database specifies this is database controlled if this is set true */
    @SerialName(value = "database")
    val database: kotlin.Boolean? = null,

    /* name of the mutex */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* Namespace is the namespace of the mutex, default: [namespace of workflow] */
    @SerialName(value = "namespace")
    val namespace: kotlin.String? = null

) {


}

