/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * MutexHolding describes the mutex and the object which is holding it.
 *
 * @param holder Holder is a reference to the object which holds the Mutex. Holding Scenario:   1. Current workflow's NodeID which is holding the lock.      e.g: ${NodeID} Waiting Scenario:   1. Current workflow or other workflow NodeID which is holding the lock.      e.g: ${WorkflowName}/${NodeID}
 * @param mutex Reference for the mutex e.g: ${namespace}/mutex/${mutexName}
 */
@Serializable

data class MutexHolding (

    /* Holder is a reference to the object which holds the Mutex. Holding Scenario:   1. Current workflow's NodeID which is holding the lock.      e.g: ${NodeID} Waiting Scenario:   1. Current workflow or other workflow NodeID which is holding the lock.      e.g: ${WorkflowName}/${NodeID} */
    @SerialName(value = "holder")
    val holder: kotlin.String? = null,

    /* Reference for the mutex e.g: ${namespace}/mutex/${mutexName} */
    @SerialName(value = "mutex")
    val mutex: kotlin.String? = null

) {


}

