/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param hooked Hooked tracks whether or not this node was triggered by hook or onExit
 * @param retried Retried tracks whether or not this node was retried by retryStrategy
 */
@Serializable

data class NodeFlag (

    /* Hooked tracks whether or not this node was triggered by hook or onExit */
    @SerialName(value = "hooked")
    val hooked: kotlin.Boolean? = null,

    /* Retried tracks whether or not this node was retried by retryStrategy */
    @SerialName(value = "retried")
    val retried: kotlin.Boolean? = null

) {


}

