/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesSecretKeySelector
import io.heapy.argo.client.models.OSSLifecycleRule

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * OSSArtifact is the location of an Alibaba Cloud OSS artifact
 *
 * @param key Key is the path in the bucket where the artifact resides
 * @param accessKeySecret 
 * @param bucket Bucket is the name of the bucket
 * @param createBucketIfNotPresent CreateBucketIfNotPresent tells the driver to attempt to create the OSS bucket for output artifacts, if it doesn't exist
 * @param endpoint Endpoint is the hostname of the bucket endpoint
 * @param lifecycleRule 
 * @param secretKeySecret 
 * @param securityToken SecurityToken is the user's temporary security token. For more details, check out: https://www.alibabacloud.com/help/doc-detail/100624.htm
 * @param useSDKCreds UseSDKCreds tells the driver to figure out credentials based on sdk defaults.
 */
@Serializable

data class OSSArtifact (

    /* Key is the path in the bucket where the artifact resides */
    @SerialName(value = "key")
    val key: kotlin.String,

    @SerialName(value = "accessKeySecret")
    val accessKeySecret: KubernetesSecretKeySelector? = null,

    /* Bucket is the name of the bucket */
    @SerialName(value = "bucket")
    val bucket: kotlin.String? = null,

    /* CreateBucketIfNotPresent tells the driver to attempt to create the OSS bucket for output artifacts, if it doesn't exist */
    @SerialName(value = "createBucketIfNotPresent")
    val createBucketIfNotPresent: kotlin.Boolean? = null,

    /* Endpoint is the hostname of the bucket endpoint */
    @SerialName(value = "endpoint")
    val endpoint: kotlin.String? = null,

    @SerialName(value = "lifecycleRule")
    val lifecycleRule: OSSLifecycleRule? = null,

    @SerialName(value = "secretKeySecret")
    val secretKeySecret: KubernetesSecretKeySelector? = null,

    /* SecurityToken is the user's temporary security token. For more details, check out: https://www.alibabacloud.com/help/doc-detail/100624.htm */
    @SerialName(value = "securityToken")
    val securityToken: kotlin.String? = null,

    /* UseSDKCreds tells the driver to figure out credentials based on sdk defaults. */
    @SerialName(value = "useSDKCreds")
    val useSDKCreds: kotlin.Boolean? = null

) {


}

