/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ApiMachineryLabelSelector

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * PodGC describes how to delete completed pods as they complete
 *
 * @param deleteDelayDuration DeleteDelayDuration specifies the duration before pods in the GC queue get deleted.
 * @param labelSelector 
 * @param strategy Strategy is the strategy to use. One of \"OnPodCompletion\", \"OnPodSuccess\", \"OnWorkflowCompletion\", \"OnWorkflowSuccess\". If unset, does not delete Pods
 */
@Serializable

data class PodGC (

    /* DeleteDelayDuration specifies the duration before pods in the GC queue get deleted. */
    @SerialName(value = "deleteDelayDuration")
    val deleteDelayDuration: kotlin.String? = null,

    @SerialName(value = "labelSelector")
    val labelSelector: ApiMachineryLabelSelector? = null,

    /* Strategy is the strategy to use. One of \"OnPodCompletion\", \"OnPodSuccess\", \"OnWorkflowCompletion\", \"OnWorkflowSuccess\". If unset, does not delete Pods */
    @SerialName(value = "strategy")
    val strategy: kotlin.String? = null

) {


}

