/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * RawArtifact allows raw string content to be placed as an artifact in a container
 *
 * @param `data` Data is the string contents of the artifact
 */
@Serializable

data class RawArtifact (

    /* Data is the string contents of the artifact */
    @SerialName(value = "data")
    val `data`: kotlin.String

) {


}

