/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.Backoff
import io.heapy.argo.client.models.RetryAffinity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * RetryStrategy provides controls on how to retry a workflow step
 *
 * @param affinity 
 * @param backoff 
 * @param expression Expression is a condition expression for when a node will be retried. If it evaluates to false, the node will not be retried and the retry strategy will be ignored
 * @param limit 
 * @param retryPolicy RetryPolicy is a policy of NodePhase statuses that will be retried
 */
@Serializable

data class RetryStrategy (

    @SerialName(value = "affinity")
    val affinity: RetryAffinity? = null,

    @SerialName(value = "backoff")
    val backoff: Backoff? = null,

    /* Expression is a condition expression for when a node will be retried. If it evaluates to false, the node will not be retried and the retry strategy will be ignored */
    @SerialName(value = "expression")
    val expression: kotlin.String? = null,

    @SerialName(value = "limit")
    val limit: kotlin.String? = null,

    /* RetryPolicy is a policy of NodePhase statuses that will be retried */
    @SerialName(value = "retryPolicy")
    val retryPolicy: kotlin.String? = null

) {


}

