/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.CreateS3BucketOptions
import io.heapy.argo.client.models.KubernetesSecretKeySelector
import io.heapy.argo.client.models.S3EncryptionOptions

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * S3Artifact is the location of an S3 artifact
 *
 * @param accessKeySecret 
 * @param bucket Bucket is the name of the bucket
 * @param caSecret 
 * @param createBucketIfNotPresent 
 * @param encryptionOptions 
 * @param endpoint Endpoint is the hostname of the bucket endpoint
 * @param insecure Insecure will connect to the service with TLS
 * @param key Key is the key in the bucket where the artifact resides
 * @param region Region contains the optional bucket region
 * @param roleARN RoleARN is the Amazon Resource Name (ARN) of the role to assume.
 * @param secretKeySecret 
 * @param sessionTokenSecret 
 * @param useSDKCreds UseSDKCreds tells the driver to figure out credentials based on sdk defaults.
 */
@Serializable

data class S3Artifact (

    @SerialName(value = "accessKeySecret")
    val accessKeySecret: KubernetesSecretKeySelector? = null,

    /* Bucket is the name of the bucket */
    @SerialName(value = "bucket")
    val bucket: kotlin.String? = null,

    @SerialName(value = "caSecret")
    val caSecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "createBucketIfNotPresent")
    val createBucketIfNotPresent: CreateS3BucketOptions? = null,

    @SerialName(value = "encryptionOptions")
    val encryptionOptions: S3EncryptionOptions? = null,

    /* Endpoint is the hostname of the bucket endpoint */
    @SerialName(value = "endpoint")
    val endpoint: kotlin.String? = null,

    /* Insecure will connect to the service with TLS */
    @SerialName(value = "insecure")
    val insecure: kotlin.Boolean? = null,

    /* Key is the key in the bucket where the artifact resides */
    @SerialName(value = "key")
    val key: kotlin.String? = null,

    /* Region contains the optional bucket region */
    @SerialName(value = "region")
    val region: kotlin.String? = null,

    /* RoleARN is the Amazon Resource Name (ARN) of the role to assume. */
    @SerialName(value = "roleARN")
    val roleARN: kotlin.String? = null,

    @SerialName(value = "secretKeySecret")
    val secretKeySecret: KubernetesSecretKeySelector? = null,

    @SerialName(value = "sessionTokenSecret")
    val sessionTokenSecret: KubernetesSecretKeySelector? = null,

    /* UseSDKCreds tells the driver to figure out credentials based on sdk defaults. */
    @SerialName(value = "useSDKCreds")
    val useSDKCreds: kotlin.Boolean? = null

) {


}

