/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param holders Holders stores the list of current holder names in the 
 * @param semaphore Semaphore stores the semaphore name.
 */
@Serializable

data class SemaphoreHolding (

    /* Holders stores the list of current holder names in the  */
    @SerialName(value = "holders")
    val holders: kotlin.collections.List<kotlin.String>? = null,

    /* Semaphore stores the semaphore name. */
    @SerialName(value = "semaphore")
    val semaphore: kotlin.String? = null

) {


}

