/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.KubernetesConfigMapKeySelector
import io.heapy.argo.client.models.SyncDatabaseRef

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * SemaphoreRef is a reference of Semaphore
 *
 * @param configMapKeyRef 
 * @param database 
 * @param namespace Namespace is the namespace of the configmap, default: [namespace of workflow]
 */
@Serializable

data class SemaphoreRef (

    @SerialName(value = "configMapKeyRef")
    val configMapKeyRef: KubernetesConfigMapKeySelector? = null,

    @SerialName(value = "database")
    val database: SyncDatabaseRef? = null,

    /* Namespace is the namespace of the configmap, default: [namespace of workflow] */
    @SerialName(value = "namespace")
    val namespace: kotlin.String? = null

) {


}

