/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ApiMachineryCreateOptions
import io.heapy.argo.client.models.ArgoEventsSensor

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createOptions 
 * @param namespace 
 * @param sensor 
 */
@Serializable

data class SensorCreateSensorRequest (

    @SerialName(value = "createOptions")
    val createOptions: ApiMachineryCreateOptions? = null,

    @SerialName(value = "namespace")
    val namespace: kotlin.String? = null,

    @SerialName(value = "sensor")
    val sensor: ArgoEventsSensor? = null

) {


}

