/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param dependencyName 
 * @param eventContext 
 * @param level 
 * @param msg 
 * @param namespace 
 * @param sensorName 
 * @param time Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
 * @param triggerName 
 */
@Serializable

data class SensorLogEntry (

    @SerialName(value = "dependencyName")
    val dependencyName: kotlin.String? = null,

    @SerialName(value = "eventContext")
    val eventContext: kotlin.String? = null,

    @SerialName(value = "level")
    val level: kotlin.String? = null,

    @SerialName(value = "msg")
    val msg: kotlin.String? = null,

    @SerialName(value = "namespace")
    val namespace: kotlin.String? = null,

    @SerialName(value = "sensorName")
    val sensorName: kotlin.String? = null,

    /* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. */
    @Contextual @SerialName(value = "time")
    val time: kotlinx.datetime.Instant? = null,

    @SerialName(value = "triggerName")
    val triggerName: kotlin.String? = null

) {


}

