/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Sequence expands a workflow step into numeric range
 *
 * @param count 
 * @param end 
 * @param format Format is a printf format string to format the value in the sequence
 * @param start 
 */
@Serializable

data class Sequence (

    @SerialName(value = "count")
    val count: kotlin.String? = null,

    @SerialName(value = "end")
    val end: kotlin.String? = null,

    /* Format is a printf format string to format the value in the sequence */
    @SerialName(value = "format")
    val format: kotlin.String? = null,

    @SerialName(value = "start")
    val start: kotlin.String? = null

) {


}

