/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.GrpcgatewayruntimeStreamError
import io.heapy.argo.client.models.SensorSensorWatchEvent

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param error 
 * @param result 
 */
@Serializable

data class StreamResultOfSensorSensorWatchEvent (

    @SerialName(value = "error")
    val error: GrpcgatewayruntimeStreamError? = null,

    @SerialName(value = "result")
    val result: SensorSensorWatchEvent? = null

) {


}

