/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ApiMachineryObjectMeta
import io.heapy.argo.client.models.Arguments
import io.heapy.argo.client.models.WorkflowTemplateRef

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param workflowTemplateRef 
 * @param arguments 
 * @param metadata 
 */
@Serializable

data class Submit (

    @SerialName(value = "workflowTemplateRef")
    val workflowTemplateRef: WorkflowTemplateRef,

    @SerialName(value = "arguments")
    val arguments: Arguments? = null,

    @SerialName(value = "metadata")
    val metadata: ApiMachineryObjectMeta? = null

) {


}

