/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.SyncSyncConfigType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param cmName 
 * @param key 
 * @param limit 
 * @param namespace 
 * @param type 
 */
@Serializable

data class SyncSyncLimitResponse (

    @SerialName(value = "cmName")
    val cmName: kotlin.String? = null,

    @SerialName(value = "key")
    val key: kotlin.String? = null,

    @SerialName(value = "limit")
    val limit: kotlin.Int? = null,

    @SerialName(value = "namespace")
    val namespace: kotlin.String? = null,

    @Contextual @SerialName(value = "type")
    val type: SyncSyncConfigType? = SyncSyncConfigType.CONFIGMAP

) {


}

