/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArtifactLocation
import io.heapy.argo.client.models.ContainerSetTemplate
import io.heapy.argo.client.models.DAGTemplate
import io.heapy.argo.client.models.Data
import io.heapy.argo.client.models.ExecutorConfig
import io.heapy.argo.client.models.HTTP
import io.heapy.argo.client.models.Inputs
import io.heapy.argo.client.models.KubernetesAffinity
import io.heapy.argo.client.models.KubernetesContainer
import io.heapy.argo.client.models.KubernetesHostAlias
import io.heapy.argo.client.models.KubernetesPodSecurityContext
import io.heapy.argo.client.models.KubernetesToleration
import io.heapy.argo.client.models.KubernetesVolume
import io.heapy.argo.client.models.Memoize
import io.heapy.argo.client.models.Metadata
import io.heapy.argo.client.models.Metrics
import io.heapy.argo.client.models.Outputs
import io.heapy.argo.client.models.ParallelSteps
import io.heapy.argo.client.models.ResourceTemplate
import io.heapy.argo.client.models.RetryStrategy
import io.heapy.argo.client.models.ScriptTemplate
import io.heapy.argo.client.models.SuspendTemplate
import io.heapy.argo.client.models.Synchronization
import io.heapy.argo.client.models.UserContainer

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Template is a reusable and composable unit of execution in a workflow
 *
 * @param activeDeadlineSeconds 
 * @param affinity 
 * @param annotations Annotations is a list of annotations to add to the template at runtime
 * @param archiveLocation 
 * @param automountServiceAccountToken AutomountServiceAccountToken indicates whether a service account token should be automatically mounted in pods. ServiceAccountName of ExecutorConfig must be specified if this value is false.
 * @param container 
 * @param containerSet 
 * @param daemon Daemon will allow a workflow to proceed to the next step so long as the container reaches readiness
 * @param dag 
 * @param `data` 
 * @param executor 
 * @param failFast FailFast, if specified, will fail this template if any of its child pods has failed. This is useful for when this template is expanded with `withItems`, etc.
 * @param hostAliases HostAliases is an optional list of hosts and IPs that will be injected into the pod spec
 * @param http 
 * @param initContainers InitContainers is a list of containers which run before the main container.
 * @param inputs 
 * @param memoize 
 * @param metadata 
 * @param metrics 
 * @param name Name is the name of the template
 * @param nodeSelector NodeSelector is a selector to schedule this step of the workflow to be run on the selected node(s). Overrides the selector set at the workflow level.
 * @param outputs 
 * @param parallelism Parallelism limits the max total parallel pods that can execute at the same time within the boundaries of this template invocation. If additional steps/dag templates are invoked, the pods created by those templates will not be counted towards this total.
 * @param plugin Plugin is an Object with exactly one key
 * @param podSpecPatch PodSpecPatch holds strategic merge patch to apply against the pod spec. Allows parameterization of container fields which are not strings (e.g. resource limits).
 * @param priorityClassName PriorityClassName to apply to workflow pods.
 * @param resource 
 * @param retryStrategy 
 * @param schedulerName If specified, the pod will be dispatched by specified scheduler. Or it will be dispatched by workflow scope scheduler if specified. If neither specified, the pod will be dispatched by default scheduler.
 * @param script 
 * @param securityContext 
 * @param serviceAccountName ServiceAccountName to apply to workflow pods
 * @param sidecars Sidecars is a list of containers which run alongside the main container Sidecars are automatically killed when the main container completes
 * @param steps Steps define a series of sequential/parallel workflow steps
 * @param `suspend` 
 * @param synchronization 
 * @param timeout Timeout allows to set the total node execution timeout duration counting from the node's start time. This duration also includes time in which the node spends in Pending state. This duration may not be applied to Step or DAG templates.
 * @param tolerations Tolerations to apply to workflow pods.
 * @param volumes Volumes is a list of volumes that can be mounted by containers in a template.
 */
@Serializable

data class Template (

    @SerialName(value = "activeDeadlineSeconds")
    val activeDeadlineSeconds: kotlin.String? = null,

    @SerialName(value = "affinity")
    val affinity: KubernetesAffinity? = null,

    /* Annotations is a list of annotations to add to the template at runtime */
    @SerialName(value = "annotations")
    val annotations: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "archiveLocation")
    val archiveLocation: ArtifactLocation? = null,

    /* AutomountServiceAccountToken indicates whether a service account token should be automatically mounted in pods. ServiceAccountName of ExecutorConfig must be specified if this value is false. */
    @SerialName(value = "automountServiceAccountToken")
    val automountServiceAccountToken: kotlin.Boolean? = null,

    @SerialName(value = "container")
    val container: KubernetesContainer? = null,

    @SerialName(value = "containerSet")
    val containerSet: ContainerSetTemplate? = null,

    /* Daemon will allow a workflow to proceed to the next step so long as the container reaches readiness */
    @SerialName(value = "daemon")
    val daemon: kotlin.Boolean? = null,

    @SerialName(value = "dag")
    val dag: DAGTemplate? = null,

    @SerialName(value = "data")
    val `data`: Data? = null,

    @SerialName(value = "executor")
    val executor: ExecutorConfig? = null,

    /* FailFast, if specified, will fail this template if any of its child pods has failed. This is useful for when this template is expanded with `withItems`, etc. */
    @SerialName(value = "failFast")
    val failFast: kotlin.Boolean? = null,

    /* HostAliases is an optional list of hosts and IPs that will be injected into the pod spec */
    @SerialName(value = "hostAliases")
    val hostAliases: kotlin.collections.List<KubernetesHostAlias>? = null,

    @SerialName(value = "http")
    val http: HTTP? = null,

    /* InitContainers is a list of containers which run before the main container. */
    @SerialName(value = "initContainers")
    val initContainers: kotlin.collections.List<UserContainer>? = null,

    @SerialName(value = "inputs")
    val inputs: Inputs? = null,

    @SerialName(value = "memoize")
    val memoize: Memoize? = null,

    @SerialName(value = "metadata")
    val metadata: Metadata? = null,

    @SerialName(value = "metrics")
    val metrics: Metrics? = null,

    /* Name is the name of the template */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* NodeSelector is a selector to schedule this step of the workflow to be run on the selected node(s). Overrides the selector set at the workflow level. */
    @SerialName(value = "nodeSelector")
    val nodeSelector: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "outputs")
    val outputs: Outputs? = null,

    /* Parallelism limits the max total parallel pods that can execute at the same time within the boundaries of this template invocation. If additional steps/dag templates are invoked, the pods created by those templates will not be counted towards this total. */
    @SerialName(value = "parallelism")
    val parallelism: kotlin.Int? = null,

    /* Plugin is an Object with exactly one key */
    @Contextual @SerialName(value = "plugin")
    val plugin: kotlin.Any? = null,

    /* PodSpecPatch holds strategic merge patch to apply against the pod spec. Allows parameterization of container fields which are not strings (e.g. resource limits). */
    @SerialName(value = "podSpecPatch")
    val podSpecPatch: kotlin.String? = null,

    /* PriorityClassName to apply to workflow pods. */
    @SerialName(value = "priorityClassName")
    val priorityClassName: kotlin.String? = null,

    @SerialName(value = "resource")
    val resource: ResourceTemplate? = null,

    @SerialName(value = "retryStrategy")
    val retryStrategy: RetryStrategy? = null,

    /* If specified, the pod will be dispatched by specified scheduler. Or it will be dispatched by workflow scope scheduler if specified. If neither specified, the pod will be dispatched by default scheduler. */
    @SerialName(value = "schedulerName")
    val schedulerName: kotlin.String? = null,

    @SerialName(value = "script")
    val script: ScriptTemplate? = null,

    @SerialName(value = "securityContext")
    val securityContext: KubernetesPodSecurityContext? = null,

    /* ServiceAccountName to apply to workflow pods */
    @SerialName(value = "serviceAccountName")
    val serviceAccountName: kotlin.String? = null,

    /* Sidecars is a list of containers which run alongside the main container Sidecars are automatically killed when the main container completes */
    @SerialName(value = "sidecars")
    val sidecars: kotlin.collections.List<UserContainer>? = null,

    /* Steps define a series of sequential/parallel workflow steps */
    @SerialName(value = "steps")
    val steps: kotlin.collections.List<@Contextual ParallelSteps>? = null,

    @SerialName(value = "suspend")
    val `suspend`: SuspendTemplate? = null,

    @SerialName(value = "synchronization")
    val synchronization: Synchronization? = null,

    /* Timeout allows to set the total node execution timeout duration counting from the node's start time. This duration also includes time in which the node spends in Pending state. This duration may not be applied to Step or DAG templates. */
    @SerialName(value = "timeout")
    val timeout: kotlin.String? = null,

    /* Tolerations to apply to workflow pods. */
    @SerialName(value = "tolerations")
    val tolerations: kotlin.collections.List<KubernetesToleration>? = null,

    /* Volumes is a list of volumes that can be mounted by containers in a template. */
    @SerialName(value = "volumes")
    val volumes: kotlin.collections.List<KubernetesVolume>? = null

) {


}

