/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * TemplateRef is a reference of template resource.
 *
 * @param clusterScope ClusterScope indicates the referred template is cluster scoped (i.e. a ClusterWorkflowTemplate).
 * @param name Name is the resource name of the template.
 * @param template Template is the name of referred template in the resource.
 */
@Serializable

data class TemplateRef (

    /* ClusterScope indicates the referred template is cluster scoped (i.e. a ClusterWorkflowTemplate). */
    @SerialName(value = "clusterScope")
    val clusterScope: kotlin.Boolean? = null,

    /* Name is the resource name of the template. */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* Template is the name of referred template in the resource. */
    @SerialName(value = "template")
    val template: kotlin.String? = null

) {


}

