/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * TTLStrategy is the strategy for the time to live depending on if the workflow succeeded or failed
 *
 * @param secondsAfterCompletion SecondsAfterCompletion is the number of seconds to live after completion
 * @param secondsAfterFailure SecondsAfterFailure is the number of seconds to live after failure
 * @param secondsAfterSuccess SecondsAfterSuccess is the number of seconds to live after success
 */
@Serializable

data class TTLStrategy (

    /* SecondsAfterCompletion is the number of seconds to live after completion */
    @SerialName(value = "secondsAfterCompletion")
    val secondsAfterCompletion: kotlin.Int? = null,

    /* SecondsAfterFailure is the number of seconds to live after failure */
    @SerialName(value = "secondsAfterFailure")
    val secondsAfterFailure: kotlin.Int? = null,

    /* SecondsAfterSuccess is the number of seconds to live after success */
    @SerialName(value = "secondsAfterSuccess")
    val secondsAfterSuccess: kotlin.Int? = null

) {


}

