/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.CronWorkflow

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param cronWorkflow 
 * @param name DEPRECATED: This field is ignored.
 * @param namespace 
 */
@Serializable

data class UpdateCronWorkflowRequest (

    @SerialName(value = "cronWorkflow")
    val cronWorkflow: CronWorkflow? = null,

    /* DEPRECATED: This field is ignored. */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "namespace")
    val namespace: kotlin.String? = null

) {


}

