/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ArtGCStatus
import io.heapy.argo.client.models.ArtifactRepositoryRefStatus
import io.heapy.argo.client.models.Condition
import io.heapy.argo.client.models.KubernetesVolume
import io.heapy.argo.client.models.NodeStatus
import io.heapy.argo.client.models.Outputs
import io.heapy.argo.client.models.SynchronizationStatus
import io.heapy.argo.client.models.Template
import io.heapy.argo.client.models.WorkflowSpec

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * WorkflowStatus contains overall status information about a workflow
 *
 * @param artifactGCStatus 
 * @param artifactRepositoryRef 
 * @param compressedNodes Compressed and base64 decoded Nodes map
 * @param conditions Conditions is a list of conditions the Workflow may have
 * @param estimatedDuration EstimatedDuration in seconds.
 * @param finishedAt Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
 * @param message A human readable message indicating details about why the workflow is in this condition.
 * @param nodes Nodes is a mapping between a node ID and the node's status.
 * @param offloadNodeStatusVersion Whether on not node status has been offloaded to a database. If exists, then Nodes and CompressedNodes will be empty. This will actually be populated with a hash of the offloaded data.
 * @param outputs 
 * @param persistentVolumeClaims PersistentVolumeClaims tracks all PVCs that were created as part of the  The contents of this list are drained at the end of the workflow.
 * @param phase Phase a simple, high-level summary of where the workflow is in its lifecycle. Will be \"\" (Unknown), \"Pending\", or \"Running\" before the workflow is completed, and \"Succeeded\", \"Failed\" or \"Error\" once the workflow has completed.
 * @param progress Progress to completion
 * @param resourcesDuration ResourcesDuration is the total for the workflow
 * @param startedAt Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
 * @param storedTemplates StoredTemplates is a mapping between a template ref and the node's status.
 * @param storedWorkflowTemplateSpec 
 * @param synchronization 
 * @param taskResultsCompletionStatus TaskResultsCompletionStatus tracks task result completion status (mapped by node ID). Used to prevent premature archiving and garbage collection.
 */
@Serializable

data class WorkflowStatus (

    @SerialName(value = "artifactGCStatus")
    val artifactGCStatus: ArtGCStatus? = null,

    @SerialName(value = "artifactRepositoryRef")
    val artifactRepositoryRef: ArtifactRepositoryRefStatus? = null,

    /* Compressed and base64 decoded Nodes map */
    @SerialName(value = "compressedNodes")
    val compressedNodes: kotlin.String? = null,

    /* Conditions is a list of conditions the Workflow may have */
    @SerialName(value = "conditions")
    val conditions: kotlin.collections.List<Condition>? = null,

    /* EstimatedDuration in seconds. */
    @SerialName(value = "estimatedDuration")
    val estimatedDuration: kotlin.Int? = null,

    /* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. */
    @Contextual @SerialName(value = "finishedAt")
    val finishedAt: kotlinx.datetime.Instant? = null,

    /* A human readable message indicating details about why the workflow is in this condition. */
    @SerialName(value = "message")
    val message: kotlin.String? = null,

    /* Nodes is a mapping between a node ID and the node's status. */
    @Contextual @SerialName(value = "nodes")
    val nodes: kotlin.collections.Map<kotlin.String, NodeStatus>? = null,

    /* Whether on not node status has been offloaded to a database. If exists, then Nodes and CompressedNodes will be empty. This will actually be populated with a hash of the offloaded data. */
    @SerialName(value = "offloadNodeStatusVersion")
    val offloadNodeStatusVersion: kotlin.String? = null,

    @SerialName(value = "outputs")
    val outputs: Outputs? = null,

    /* PersistentVolumeClaims tracks all PVCs that were created as part of the  The contents of this list are drained at the end of the workflow. */
    @SerialName(value = "persistentVolumeClaims")
    val persistentVolumeClaims: kotlin.collections.List<KubernetesVolume>? = null,

    /* Phase a simple, high-level summary of where the workflow is in its lifecycle. Will be \"\" (Unknown), \"Pending\", or \"Running\" before the workflow is completed, and \"Succeeded\", \"Failed\" or \"Error\" once the workflow has completed. */
    @SerialName(value = "phase")
    val phase: kotlin.String? = null,

    /* Progress to completion */
    @SerialName(value = "progress")
    val progress: kotlin.String? = null,

    /* ResourcesDuration is the total for the workflow */
    @SerialName(value = "resourcesDuration")
    val resourcesDuration: kotlin.collections.Map<kotlin.String, kotlin.Long>? = null,

    /* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. */
    @Contextual @SerialName(value = "startedAt")
    val startedAt: kotlinx.datetime.Instant? = null,

    /* StoredTemplates is a mapping between a template ref and the node's status. */
    @Contextual @SerialName(value = "storedTemplates")
    val storedTemplates: kotlin.collections.Map<kotlin.String, Template>? = null,

    @SerialName(value = "storedWorkflowTemplateSpec")
    val storedWorkflowTemplateSpec: WorkflowSpec? = null,

    @SerialName(value = "synchronization")
    val synchronization: SynchronizationStatus? = null,

    /* TaskResultsCompletionStatus tracks task result completion status (mapped by node ID). Used to prevent premature archiving and garbage collection. */
    @SerialName(value = "taskResultsCompletionStatus")
    val taskResultsCompletionStatus: kotlin.collections.Map<kotlin.String, kotlin.Boolean>? = null

) {


}

