/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.Workflow

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param namespace 
 * @param workflow 
 */
@Serializable

data class WorkflowLintRequest (

    @SerialName(value = "namespace")
    val namespace: kotlin.String? = null,

    @SerialName(value = "workflow")
    val workflow: Workflow? = null

) {


}

