/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param memoized 
 * @param name 
 * @param namespace 
 * @param parameters 
 */
@Serializable

data class WorkflowResubmitRequest (

    @SerialName(value = "memoized")
    val memoized: kotlin.Boolean? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "namespace")
    val namespace: kotlin.String? = null,

    @SerialName(value = "parameters")
    val parameters: kotlin.collections.List<kotlin.String>? = null

) {


}

