/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.Arguments
import io.heapy.argo.client.models.ArtifactRepositoryRef
import io.heapy.argo.client.models.ExecutorConfig
import io.heapy.argo.client.models.Iok8sapipolicyv1PodDisruptionBudgetSpec
import io.heapy.argo.client.models.KubernetesAffinity
import io.heapy.argo.client.models.KubernetesHostAlias
import io.heapy.argo.client.models.KubernetesLocalObjectReference
import io.heapy.argo.client.models.KubernetesPersistentVolumeClaim
import io.heapy.argo.client.models.KubernetesPodDNSConfig
import io.heapy.argo.client.models.KubernetesPodSecurityContext
import io.heapy.argo.client.models.KubernetesToleration
import io.heapy.argo.client.models.KubernetesVolume
import io.heapy.argo.client.models.LifecycleHook
import io.heapy.argo.client.models.Metadata
import io.heapy.argo.client.models.Metrics
import io.heapy.argo.client.models.PodGC
import io.heapy.argo.client.models.RetryStrategy
import io.heapy.argo.client.models.Synchronization
import io.heapy.argo.client.models.TTLStrategy
import io.heapy.argo.client.models.Template
import io.heapy.argo.client.models.VolumeClaimGC
import io.heapy.argo.client.models.WorkflowLevelArtifactGC
import io.heapy.argo.client.models.WorkflowMetadata
import io.heapy.argo.client.models.WorkflowTemplateRef

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * WorkflowSpec is the specification of a Workflow.
 *
 * @param activeDeadlineSeconds Optional duration in seconds relative to the workflow start time which the workflow is allowed to run before the controller terminates the  A value of zero is used to terminate a Running workflow
 * @param affinity 
 * @param archiveLogs ArchiveLogs indicates if the container logs should be archived
 * @param arguments 
 * @param artifactGC 
 * @param artifactRepositoryRef 
 * @param automountServiceAccountToken AutomountServiceAccountToken indicates whether a service account token should be automatically mounted in pods. ServiceAccountName of ExecutorConfig must be specified if this value is false.
 * @param dnsConfig 
 * @param dnsPolicy Set DNS policy for workflow pods. Defaults to \"ClusterFirst\". Valid values are 'ClusterFirstWithHostNet', 'ClusterFirst', 'Default' or 'None'. DNS parameters given in DNSConfig will be merged with the policy selected with DNSPolicy. To have DNS options set along with hostNetwork, you have to specify DNS policy explicitly to 'ClusterFirstWithHostNet'.
 * @param entrypoint Entrypoint is a template reference to the starting point of the 
 * @param executor 
 * @param hooks Hooks holds the lifecycle hook which is invoked at lifecycle of step, irrespective of the success, failure, or error status of the primary step
 * @param hostAliases 
 * @param hostNetwork Host networking requested for this workflow pod. Default to false.
 * @param imagePullSecrets ImagePullSecrets is a list of references to secrets in the same namespace to use for pulling any images in pods that reference this ServiceAccount. ImagePullSecrets are distinct from Secrets because Secrets can be mounted in the pod, but ImagePullSecrets are only accessed by the kubelet. More info: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
 * @param metrics 
 * @param nodeSelector NodeSelector is a selector which will result in all pods of the workflow to be scheduled on the selected node(s). This is able to be overridden by a nodeSelector specified in the template.
 * @param onExit OnExit is a template reference which is invoked at the end of the workflow, irrespective of the success, failure, or error of the primary 
 * @param parallelism Parallelism limits the max total parallel pods that can execute at the same time in a workflow
 * @param podDisruptionBudget 
 * @param podGC 
 * @param podMetadata 
 * @param podPriorityClassName PriorityClassName to apply to workflow pods.
 * @param podSpecPatch PodSpecPatch holds strategic merge patch to apply against the pod spec. Allows parameterization of container fields which are not strings (e.g. resource limits).
 * @param priority Priority is used if controller is configured to process limited number of workflows in parallel. Workflows with higher priority are processed first.
 * @param retryStrategy 
 * @param schedulerName Set scheduler name for all pods. Will be overridden if container/script template's scheduler name is set. Default scheduler will be used if neither specified.
 * @param securityContext 
 * @param serviceAccountName ServiceAccountName is the name of the ServiceAccount to run all pods of the workflow as.
 * @param shutdown Shutdown will shutdown the workflow according to its ShutdownStrategy
 * @param `suspend` Suspend will suspend the workflow and prevent execution of any future steps in the workflow
 * @param synchronization 
 * @param templateDefaults 
 * @param templates Templates is a list of workflow templates used in a workflow
 * @param tolerations Tolerations to apply to workflow pods.
 * @param ttlStrategy 
 * @param volumeClaimGC 
 * @param volumeClaimTemplates VolumeClaimTemplates is a list of claims that containers are allowed to reference. The Workflow controller will create the claims at the beginning of the workflow and delete the claims upon completion of the workflow
 * @param volumes Volumes is a list of volumes that can be mounted by containers in a 
 * @param workflowMetadata 
 * @param workflowTemplateRef 
 */
@Serializable

data class WorkflowSpec (

    /* Optional duration in seconds relative to the workflow start time which the workflow is allowed to run before the controller terminates the  A value of zero is used to terminate a Running workflow */
    @SerialName(value = "activeDeadlineSeconds")
    val activeDeadlineSeconds: kotlin.Int? = null,

    @SerialName(value = "affinity")
    val affinity: KubernetesAffinity? = null,

    /* ArchiveLogs indicates if the container logs should be archived */
    @SerialName(value = "archiveLogs")
    val archiveLogs: kotlin.Boolean? = null,

    @SerialName(value = "arguments")
    val arguments: Arguments? = null,

    @SerialName(value = "artifactGC")
    val artifactGC: WorkflowLevelArtifactGC? = null,

    @SerialName(value = "artifactRepositoryRef")
    val artifactRepositoryRef: ArtifactRepositoryRef? = null,

    /* AutomountServiceAccountToken indicates whether a service account token should be automatically mounted in pods. ServiceAccountName of ExecutorConfig must be specified if this value is false. */
    @SerialName(value = "automountServiceAccountToken")
    val automountServiceAccountToken: kotlin.Boolean? = null,

    @SerialName(value = "dnsConfig")
    val dnsConfig: KubernetesPodDNSConfig? = null,

    /* Set DNS policy for workflow pods. Defaults to \"ClusterFirst\". Valid values are 'ClusterFirstWithHostNet', 'ClusterFirst', 'Default' or 'None'. DNS parameters given in DNSConfig will be merged with the policy selected with DNSPolicy. To have DNS options set along with hostNetwork, you have to specify DNS policy explicitly to 'ClusterFirstWithHostNet'. */
    @SerialName(value = "dnsPolicy")
    val dnsPolicy: kotlin.String? = null,

    /* Entrypoint is a template reference to the starting point of the  */
    @SerialName(value = "entrypoint")
    val entrypoint: kotlin.String? = null,

    @SerialName(value = "executor")
    val executor: ExecutorConfig? = null,

    /* Hooks holds the lifecycle hook which is invoked at lifecycle of step, irrespective of the success, failure, or error status of the primary step */
    @Contextual @SerialName(value = "hooks")
    val hooks: kotlin.collections.Map<kotlin.String, LifecycleHook>? = null,

    @SerialName(value = "hostAliases")
    val hostAliases: kotlin.collections.List<KubernetesHostAlias>? = null,

    /* Host networking requested for this workflow pod. Default to false. */
    @SerialName(value = "hostNetwork")
    val hostNetwork: kotlin.Boolean? = null,

    /* ImagePullSecrets is a list of references to secrets in the same namespace to use for pulling any images in pods that reference this ServiceAccount. ImagePullSecrets are distinct from Secrets because Secrets can be mounted in the pod, but ImagePullSecrets are only accessed by the kubelet. More info: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod */
    @SerialName(value = "imagePullSecrets")
    val imagePullSecrets: kotlin.collections.List<KubernetesLocalObjectReference>? = null,

    @SerialName(value = "metrics")
    val metrics: Metrics? = null,

    /* NodeSelector is a selector which will result in all pods of the workflow to be scheduled on the selected node(s). This is able to be overridden by a nodeSelector specified in the template. */
    @SerialName(value = "nodeSelector")
    val nodeSelector: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* OnExit is a template reference which is invoked at the end of the workflow, irrespective of the success, failure, or error of the primary  */
    @SerialName(value = "onExit")
    val onExit: kotlin.String? = null,

    /* Parallelism limits the max total parallel pods that can execute at the same time in a workflow */
    @SerialName(value = "parallelism")
    val parallelism: kotlin.Int? = null,

    @SerialName(value = "podDisruptionBudget")
    val podDisruptionBudget: Iok8sapipolicyv1PodDisruptionBudgetSpec? = null,

    @SerialName(value = "podGC")
    val podGC: PodGC? = null,

    @SerialName(value = "podMetadata")
    val podMetadata: Metadata? = null,

    /* PriorityClassName to apply to workflow pods. */
    @SerialName(value = "podPriorityClassName")
    val podPriorityClassName: kotlin.String? = null,

    /* PodSpecPatch holds strategic merge patch to apply against the pod spec. Allows parameterization of container fields which are not strings (e.g. resource limits). */
    @SerialName(value = "podSpecPatch")
    val podSpecPatch: kotlin.String? = null,

    /* Priority is used if controller is configured to process limited number of workflows in parallel. Workflows with higher priority are processed first. */
    @SerialName(value = "priority")
    val priority: kotlin.Int? = null,

    @SerialName(value = "retryStrategy")
    val retryStrategy: RetryStrategy? = null,

    /* Set scheduler name for all pods. Will be overridden if container/script template's scheduler name is set. Default scheduler will be used if neither specified. */
    @SerialName(value = "schedulerName")
    val schedulerName: kotlin.String? = null,

    @SerialName(value = "securityContext")
    val securityContext: KubernetesPodSecurityContext? = null,

    /* ServiceAccountName is the name of the ServiceAccount to run all pods of the workflow as. */
    @SerialName(value = "serviceAccountName")
    val serviceAccountName: kotlin.String? = null,

    /* Shutdown will shutdown the workflow according to its ShutdownStrategy */
    @SerialName(value = "shutdown")
    val shutdown: kotlin.String? = null,

    /* Suspend will suspend the workflow and prevent execution of any future steps in the workflow */
    @SerialName(value = "suspend")
    val `suspend`: kotlin.Boolean? = null,

    @SerialName(value = "synchronization")
    val synchronization: Synchronization? = null,

    @SerialName(value = "templateDefaults")
    val templateDefaults: Template? = null,

    /* Templates is a list of workflow templates used in a workflow */
    @SerialName(value = "templates")
    val templates: kotlin.collections.List<Template>? = null,

    /* Tolerations to apply to workflow pods. */
    @SerialName(value = "tolerations")
    val tolerations: kotlin.collections.List<KubernetesToleration>? = null,

    @SerialName(value = "ttlStrategy")
    val ttlStrategy: TTLStrategy? = null,

    @SerialName(value = "volumeClaimGC")
    val volumeClaimGC: VolumeClaimGC? = null,

    /* VolumeClaimTemplates is a list of claims that containers are allowed to reference. The Workflow controller will create the claims at the beginning of the workflow and delete the claims upon completion of the workflow */
    @SerialName(value = "volumeClaimTemplates")
    val volumeClaimTemplates: kotlin.collections.List<KubernetesPersistentVolumeClaim>? = null,

    /* Volumes is a list of volumes that can be mounted by containers in a  */
    @SerialName(value = "volumes")
    val volumes: kotlin.collections.List<KubernetesVolume>? = null,

    @SerialName(value = "workflowMetadata")
    val workflowMetadata: WorkflowMetadata? = null,

    @SerialName(value = "workflowTemplateRef")
    val workflowTemplateRef: WorkflowTemplateRef? = null

) {


}

