/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param namespace 
 */
@Serializable

data class WorkflowSuspendRequest (

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "namespace")
    val namespace: kotlin.String? = null

) {


}

