/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.Metadata

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * WorkflowLevelArtifactGC describes how to delete artifacts from completed Workflows - this spec is used on the Workflow level
 *
 * @param forceFinalizerRemoval ForceFinalizerRemoval: if set to true, the finalizer will be removed in the case that Artifact GC fails
 * @param podMetadata 
 * @param podSpecPatch PodSpecPatch holds strategic merge patch to apply against the artgc pod spec.
 * @param serviceAccountName ServiceAccountName is an optional field for specifying the Service Account that should be assigned to the Pod doing the deletion
 * @param strategy Strategy is the strategy to use.
 */
@Serializable

data class WorkflowLevelArtifactGC (

    /* ForceFinalizerRemoval: if set to true, the finalizer will be removed in the case that Artifact GC fails */
    @SerialName(value = "forceFinalizerRemoval")
    val forceFinalizerRemoval: kotlin.Boolean? = null,

    @SerialName(value = "podMetadata")
    val podMetadata: Metadata? = null,

    /* PodSpecPatch holds strategic merge patch to apply against the artgc pod spec. */
    @SerialName(value = "podSpecPatch")
    val podSpecPatch: kotlin.String? = null,

    /* ServiceAccountName is an optional field for specifying the Service Account that should be assigned to the Pod doing the deletion */
    @SerialName(value = "serviceAccountName")
    val serviceAccountName: kotlin.String? = null,

    /* Strategy is the strategy to use. */
    @SerialName(value = "strategy")
    val strategy: kotlin.String? = null

) {


}

