/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.Event
import io.heapy.argo.client.models.Submit

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param event 
 * @param submit 
 */
@Serializable

data class WorkflowEventBindingSpec (

    @SerialName(value = "event")
    val event: Event,

    @SerialName(value = "submit")
    val submit: Submit? = null

) {


}

