/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.ApiMachineryCreateOptions
import io.heapy.argo.client.models.Workflow

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createOptions 
 * @param instanceID This field is no longer used.
 * @param namespace 
 * @param serverDryRun 
 * @param workflow 
 */
@Serializable

data class WorkflowCreateRequest (

    @SerialName(value = "createOptions")
    val createOptions: ApiMachineryCreateOptions? = null,

    /* This field is no longer used. */
    @SerialName(value = "instanceID")
    val instanceID: kotlin.String? = null,

    @SerialName(value = "namespace")
    val namespace: kotlin.String? = null,

    @SerialName(value = "serverDryRun")
    val serverDryRun: kotlin.Boolean? = null,

    @SerialName(value = "workflow")
    val workflow: Workflow? = null

) {


}

