/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.models

import io.heapy.argo.client.models.Workflow

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `object` 
 * @param type 
 */
@Serializable

data class WorkflowWatchEvent (

    @SerialName(value = "object")
    val `object`: Workflow? = null,

    @SerialName(value = "type")
    val type: kotlin.String? = null

) {


}

