/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.apis

import io.heapy.argo.client.models.GrpcgatewayruntimeError

import io.heapy.argo.client.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class ArtifactServiceApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * Get an artifact.
        * 
         * @param namespace  
         * @param idDiscriminator  
         * @param id  
         * @param nodeId  
         * @param artifactName  
         * @param artifactDiscriminator  
         * @return java.io.File
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun artifactServiceGetArtifactFile(namespace: kotlin.String, idDiscriminator: kotlin.String, id: kotlin.String, nodeId: kotlin.String, artifactName: kotlin.String, artifactDiscriminator: kotlin.String): HttpResponse<java.io.File> {

            val localVariableAuthNames = listOf<String>("BearerToken")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/artifact-files/{namespace}/{idDiscriminator}/{id}/{nodeId}/{artifactDiscriminator}/{artifactName}".replace("{" + "namespace" + "}", "$namespace").replace("{" + "idDiscriminator" + "}", "$idDiscriminator").replace("{" + "id" + "}", "$id").replace("{" + "nodeId" + "}", "$nodeId").replace("{" + "artifactName" + "}", "$artifactName").replace("{" + "artifactDiscriminator" + "}", "$artifactDiscriminator"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * Get an input artifact.
        * 
         * @param namespace  
         * @param name  
         * @param nodeId  
         * @param artifactName  
         * @return java.io.File
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun artifactServiceGetInputArtifact(namespace: kotlin.String, name: kotlin.String, nodeId: kotlin.String, artifactName: kotlin.String): HttpResponse<java.io.File> {

            val localVariableAuthNames = listOf<String>("BearerToken")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/input-artifacts/{namespace}/{name}/{nodeId}/{artifactName}".replace("{" + "namespace" + "}", "$namespace").replace("{" + "name" + "}", "$name").replace("{" + "nodeId" + "}", "$nodeId").replace("{" + "artifactName" + "}", "$artifactName"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * Get an input artifact by UID.
        * 
         * @param uid  
         * @param nodeId  
         * @param artifactName  
         * @return java.io.File
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun artifactServiceGetInputArtifactByUID(uid: kotlin.String, nodeId: kotlin.String, artifactName: kotlin.String): HttpResponse<java.io.File> {

            val localVariableAuthNames = listOf<String>("BearerToken")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/input-artifacts-by-uid/{uid}/{nodeId}/{artifactName}".replace("{" + "uid" + "}", "$uid").replace("{" + "nodeId" + "}", "$nodeId").replace("{" + "artifactName" + "}", "$artifactName"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * Get an output artifact.
        * 
         * @param namespace  
         * @param name  
         * @param nodeId  
         * @param artifactName  
         * @return java.io.File
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun artifactServiceGetOutputArtifact(namespace: kotlin.String, name: kotlin.String, nodeId: kotlin.String, artifactName: kotlin.String): HttpResponse<java.io.File> {

            val localVariableAuthNames = listOf<String>("BearerToken")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/artifacts/{namespace}/{name}/{nodeId}/{artifactName}".replace("{" + "namespace" + "}", "$namespace").replace("{" + "name" + "}", "$name").replace("{" + "nodeId" + "}", "$nodeId").replace("{" + "artifactName" + "}", "$artifactName"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * Get an output artifact by UID.
        * 
         * @param uid  
         * @param nodeId  
         * @param artifactName  
         * @return java.io.File
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun artifactServiceGetOutputArtifactByUID(uid: kotlin.String, nodeId: kotlin.String, artifactName: kotlin.String): HttpResponse<java.io.File> {

            val localVariableAuthNames = listOf<String>("BearerToken")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/artifacts-by-uid/{uid}/{nodeId}/{artifactName}".replace("{" + "uid" + "}", "$uid").replace("{" + "nodeId" + "}", "$nodeId").replace("{" + "artifactName" + "}", "$artifactName"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
