/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.heapy.argo.client.apis

import io.heapy.argo.client.models.GrpcgatewayruntimeError
import io.heapy.argo.client.models.SyncCreateSyncLimitRequest
import io.heapy.argo.client.models.SyncSyncLimitResponse
import io.heapy.argo.client.models.SyncUpdateSyncLimitRequest

import io.heapy.argo.client.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class SyncServiceApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * 
        * 
         * @param namespace  
         * @param body  
         * @return SyncSyncLimitResponse
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun syncServiceCreateSyncLimit(namespace: kotlin.String, body: SyncCreateSyncLimitRequest): HttpResponse<SyncSyncLimitResponse> {

            val localVariableAuthNames = listOf<String>("BearerToken")

            val localVariableBody = body

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/sync/{namespace}".replace("{" + "namespace" + "}", "$namespace"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * 
        * 
         * @param namespace  
         * @param key  
         * @param type  (optional, default to CONFIGMAP)
         * @param cmName  (optional)
         * @return kotlin.Any
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun syncServiceDeleteSyncLimit(namespace: kotlin.String, key: kotlin.String, type: kotlin.String?, cmName: kotlin.String?): HttpResponse<kotlin.Any> {

            val localVariableAuthNames = listOf<String>("BearerToken")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            type?.apply { localVariableQuery["type"] = listOf("$type") }
            cmName?.apply { localVariableQuery["cmName"] = listOf("$cmName") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v1/sync/{namespace}/{key}".replace("{" + "namespace" + "}", "$namespace").replace("{" + "key" + "}", "$key"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * 
        * 
         * @param namespace  
         * @param key  
         * @param type  (optional, default to CONFIGMAP)
         * @param cmName  (optional)
         * @return SyncSyncLimitResponse
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun syncServiceGetSyncLimit(namespace: kotlin.String, key: kotlin.String, type: kotlin.String?, cmName: kotlin.String?): HttpResponse<SyncSyncLimitResponse> {

            val localVariableAuthNames = listOf<String>("BearerToken")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            type?.apply { localVariableQuery["type"] = listOf("$type") }
            cmName?.apply { localVariableQuery["cmName"] = listOf("$cmName") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/sync/{namespace}/{key}".replace("{" + "namespace" + "}", "$namespace").replace("{" + "key" + "}", "$key"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * 
        * 
         * @param namespace  
         * @param key  
         * @param body  
         * @return SyncSyncLimitResponse
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun syncServiceUpdateSyncLimit(namespace: kotlin.String, key: kotlin.String, body: SyncUpdateSyncLimitRequest): HttpResponse<SyncSyncLimitResponse> {

            val localVariableAuthNames = listOf<String>("BearerToken")

            val localVariableBody = body

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/api/v1/sync/{namespace}/{key}".replace("{" + "namespace" + "}", "$namespace").replace("{" + "key" + "}", "$key"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
